import 'package:adblock_rule_parser/adblock_rule_parser.dart';

void log(String message) {
  print(message);
}
void main() {
  final rules = [
    '''||d2wlwbnaa4keje.cloudfront.net^\$script,image''',
    'm.youtube.com,music.youtube.com#\$#override-property-read yt.ads.biscotti.lastId_ undefined',
    'studme.org#\$#abort-on-property-read _0x5443',
    '-1688-wp-media/ads/',
    '!--fdsa-',
    'null',
    'google.com',
'''super.cz##img[id^="rs-bg-img"]''',
'''super.cz##div[class*="color-0"]''',
'''super.cz##div[id*="superPrclanek-"][class\$="timeline-content"]''',
'''kinobox.cz,nasepenize.cz###stickyBanner''',
'''kinobox.cz##.box.banner_300, #b300_fixbox''',
'''kinobox.cz,nasepenize.cz##.btitle-right''',
'''kinobox.cz,nasepenize.cz##a[href*="IdBnrP="][href*="IdCamp="]''',
'''kinobox.cz,nasepenize.cz##[id^="pxBanner"]''',
'''kinobox.cz,nasepenize.cz##a.click-layer#clickLayer''',
'''nasepenize.cz##a[target="_blank"][class="tracked-event"]>img:only-child''',
'''kinobox.cz###stickyWrap''',
'''kinobox.cz,nasepenize.cz##a[target="_blank"]>img[class*="-click-"]''',
'''kinobox.cz,nasepenize.cz##.sticky[stickystop]''',
'''kinobox.cz,nasepenize.cz##[class\$=" sticky"]''',
'''kinobox.cz,nasepenize.cz##div[class\$="-rightcJ"]''',
'''kinobox.cz,nasepenize.cz,fights.cz,spisovatele.cz##.SC_TBlock''',
'''kinobox.cz,nasepenize.cz,fights.cz##.pe-link''',
'''kinobox.cz,nasepenize.cz,fights.cz##.wrap-advert''',
'''kinobox.cz,nasepenize.cz,fights.cz##.quaquaquakva''',
'''kinobox.cz,nasepenize.cz,fights.cz##[href*=";cdata="]''',
'''fights.cz###desktop-square-top, #desktop-leader-top, .desktop-square-top, .desktop-leader-top''',
'''fights.cz##.banner-add''',
'''nasepenize.cz###side-offer-wrap''',
'''nasepenize.cz#?#:-abp-has(>[class\$="selfpromo"])''',
'''kinobox.cz,nasepenize.cz,fights.cz##[id*="tmAdVideo"], [class=" pe-banner"]''',
'''fights.cz,spisovatele.cz##body>a[target="_blank"]''',
'''/dynamic^\$image,domain=kupi.cz''',
'''||super.cz/*&*=\$subdocument,domain=super.cz''',
'''||sport.cz/*&*=\$subdocument,domain=sport.cz''',
'''||www.kupi.cz/*&*=\$subdocument,domain=www.kupi.cz''',
'''||seznamzpravy.cz/*/static/js/*^\$domain=seznamzpravy.cz''',
'''seznamzpravy.cz/*seznamzpravy.cz\$subdocument''',
'''seznamzpravy.cz/*ssp.js''',
'''seznamzpravy.cz/*cmp*\$script''',
'''novinky.cz,super.cz,sport.cz,seznamzpravy.cz,kupi.cz,horoskopy.cz##[data-cy], [data-e2e-advert], a[href*="adurl="]''',
'''novinky.cz,super.cz,sport.cz,kupi.cz##.burRman''',
'''novinky.cz,super.cz,sport.cz,horoskopy.cz##div[data-impressionurl]''',
'''novinky.cz,super.cz,sport.cz,seznamzpravy.cz,horoskopy.cz##.sssp-posCont, .sssp-resizeCont''',
'''novinky.cz,super.cz,sport.cz,seznamzpravy.cz,horoskopy.cz#?#div:-abp-has(>p:-abp-contains(Reklama))''',
'''novinky.cz,super.cz,sport.cz,seznamzpravy.cz,horoskopy.cz#\$#abort-on-property-write sssp''',
'''novinky.cz,super.cz,sport.cz,seznamzpravy.cz,kupi.cz##[data-e2e-zoneid]''',
'''novinky.cz,super.cz,sport.cz,kupi.cz###adCommercialBackground''',
'''novinky.cz,super.cz,sport.cz,kupi.cz##.ads''',
'''novinky.cz,super.cz,sport.cz,kupi.cz##.Rggheysn''',
'''novinky.cz,super.cz,sport.cz,kupi.cz##.combi__ad''',
'''novinky.cz,super.cz,sport.cz,kupi.cz##.dynamic_Rggheysn''',
'''novinky.cz,kupi.cz,sport.cz,super.cz##._ad_branding_container''',
'''novinky.cz,super.cz,sport.cz,kupi.cz##iframe[data-cy-loaded]''',
'''novinky.cz,kupi.cz,sport.cz,super.cz##.superPrclanek''',
'''super.cz##.sklikReklama''',
'''kupi.cz##[data-sssp]''',
'''seznamzpravy.cz##article[data-dot="mol-timeline-item-advert"]''',
'''seznamzpravy.cz##[class^="dynamic_banner"]''',
'''seznamzpravy.cz#\$#abort-on-property-write Object.prototype.writeAd''',
'''seznamzpravy.cz#\$#abort-on-property-write sznIVA''',
'''seznamzpravy.cz#\$#override-property-read Object.prototype.antiAdblock.postMessageSentinel null''',
'''seznamzpravy.cz#\$#override-property-read Object.prototype.aabPagePostMessageType false''',
'''seznamzpravy.cz#\$#prevent-listener message window.top''',
'''seznamzpravy.cz#\$#hide-if-contains-visible-text /Rek̃lama/ 'div[class*="g_bd"]''',
'''novinky.cz,kupi.cz,sport.cz,super.cz##.Aldremas, .plachta-middle''',
'''novinky.cz,kupi.cz,sport.cz,super.cz##iframe[data-cx-loaded]''',
'''novinky.cz,kupi.cz,sport.cz,super.cz##.plachta-overall-img''',
'''sport.cz##.combi_text__ad''',
'''sport.cz##div#page > .combi''',
'''sport.cz##div[class*="ogm-advert-static"]''',
'''sport.cz##li[class\$="ogm-timeline-advert"]''',
'''sport.cz###adSklikUnderArticle''',
'''novinky.cz,kupi.cz,sport.cz,super.cz##[id^="tetrahedron"], .tetrahedron''',
'''novinky.cz,kupi.cz,sport.cz,super.cz##[data-e4e-advert], .basafoxy''',
'''novinky.cz,kupi.cz,sport.cz,super.cz##.oktagram_image''',
'''novinky.cz,kupi.cz,sport.cz,super.cz##.oktapoid, [id^="oktapoid"]''',
'''novinky.cz,kupi.cz,sport.cz,super.cz##a[title="R_eklama"]''',
'''novinky.cz,kupi.cz,sport.cz,super.cz##[data-e11i="ogm-branding-advert"], [class="combi"]''',
'''novinky.cz,kupi.cz,sport.cz,super.cz##[class\$="Flax"]''',
'''novinky.cz,kupi.cz,sport.cz,super.cz##[id\$="-ad-container"]''',
'''novinky.cz,kupi.cz,sport.cz,super.cz###sf0''',
'''novinky.cz,kupi.cz,sport.cz,super.cz##a[title="Rekᥣama"]''',
'''novinky.cz,kupi.cz,sport.cz,super.cz##a[href*="__CLICKTHRU__"]''',
'''novinky.cz,kupi.cz,sport.cz,super.cz,horoskopy.cz##[class\$="ad-wrapper"]''',
'''novinky.cz,kupi.cz,sport.cz,super.cz,horoskopy.cz##a[href*="adfibeg="]''',
'''novinky.cz,kupi.cz,sport.cz,super.cz,horoskopy.cz##a[href*="adcurl="]''',
'''novinky.cz,kupi.cz,sport.cz,super.cz,horoskopy.cz##a[href*="adblock"]''',
'''novinky.cz,kupi.cz,sport.cz,super.cz,horoskopy.cz##a[href*="?adocurl"]''',
'''novinky.cz,kupi.cz,sport.cz,super.cz,horoskopy.cz##a[href*="_goes_through_the_woods="]''',
'''novinky.cz,kupi.cz,sport.cz,super.cz,horoskopy.cz##a[href*="klik"][href*="truu"]''',
'''novinky.cz,kupi.cz,sport.cz,super.cz,horoskopy.cz##a[href*="/bimbu?"]''',
'''novinky.cz,kupi.cz,sport.cz,super.cz,horoskopy.cz##a[href*="adb"][href*="collocation="]''',
'''novinky.cz,kupi.cz,sport.cz,super.cz,horoskopy.cz##[id^="adPrClanek_"]''',
'''novinky.cz,kupi.cz,sport.cz,super.cz,horoskopy.cz##[href*="herm"][href*="seznam"]''',
'''novinky.cz,kupi.cz,sport.cz,super.cz,horoskopy.cz##.ssp_top''',
'''novinky.cz,kupi.cz,sport.cz,super.cz,horoskopy.cz##[href*="Seznam_"][href*="adb"]''',
'''novinky.cz,kupi.cz,sport.cz,super.cz,horoskopy.cz##[href*="/pimpu?"]''',
'''novinky.cz,kupi.cz,sport.cz,super.cz,horoskopy.cz##[href*="_Branding"]''',
'''novinky.cz,kupi.cz,sport.cz,super.cz,horoskopy.cz##[href*="_leaderboard"]''',
'''novinky.cz,kupi.cz,sport.cz,super.cz,horoskopy.cz##iframe[frameborder="no"][scrolling="no"][style*="display: block;"]''',
'''novinky.cz,kupi.cz,sport.cz,super.cz,horoskopy.cz##iframe[hehehe="no"][scrolling="no"][style*="display: block;"]''',
'''novinky.cz##a[title="Rekɭama"]''',
'''novinky.cz##[class*="feed-item-advert"]''',
'''novinky.cz##a[href*=";CREFURL="]''',
'''novinky.cz,kupi.cz,sport.cz,super.cz,horoskopy.cz##[id^="outstream_container_"]''',
'''novinky.cz,kupi.cz,sport.cz,super.cz,horoskopy.cz###sznad-video-takeover''',
'''novinky.cz,kupi.cz,sport.cz,super.cz,horoskopy.cz##[data-blahakvaka]''',
'''novinky.cz##a[href*="&partId="]''',
'''novinky.cz##a[title][target="_blank"][href^="//www.novinky.cz/"]''',
'''novinky.cz##div[style^="background-Image:"], [style^="bACkgrOund-imAge:"]''',
'''sport.cz##iframe[frameborder][scrolling][src^="https://www.sport.cz/"]''',
'''super.cz##iframe[frameborder][scrolling][src^="https://www.super.cz/"]''',
'''novinky.cz,kupi.cz,sport.cz,super.cz,horoskopy.cz##iframe[frameporder]''',
'''kupi.cz##iframe[frameborder][scrolling][src^="https://www.kupi.cz/"]''',
'''kupi.cz##[class\$="_ssp"], [class^="ssp_"]''',
'''novinky.cz,sport.cz,super.cz##[class\$="_main__ad"]''',
'''novinky.cz,kupi.cz,sport.cz,super.cz,horoskopy.cz##[id^="branding-"]''',
'''novinky.cz,kupi.cz,sport.cz,super.cz,horoskopy.cz##[data-oblohakava]''',
'''novinky.cz,kupi.cz,sport.cz,super.cz,horoskopy.cz##iframe[ramefamorderx]''',
'''novinky.cz,kupi.cz,sport.cz,super.cz,horoskopy.cz##._ad_branding_positioner''',
'''novinky.cz,kupi.cz,sport.cz,super.cz,horoskopy.cz##a[href*="BANNER"]''',
'''novinky.cz,kupi.cz,sport.cz,super.cz,horoskopy.cz##a[href*="ghx_content"]''',
'''novinky.cz##article[data-dot^="advert-item"]''',
'''novinky.cz##section[role^="complementary"]''',
'''novinky.cz##div[class*="advert-static"]''',
'''novinky.cz##div[class*="banner-ad"]''',
'''novinky.cz##article[class\$="advert-item--default"]''',
'''novinky.cz##img[src*="1T4PK70hS2C"]''',
'''novinky.cz,super.cz,sport.cz##.barMan''',
'''novinky.cz,seznamzpravy.cz,sport.cz##div[data-adtrackingtemporaryurl]''',
'''novinky.cz,seznamzpravy.cz,sport.cz##div[style="background-color: rgb(255, 255, 255);"] > a[href][target="_blank"]''',
'''ahaonline.czinfo.cz,onetv.cz##a[href*="verdsi="][href*="&ip="]''',
'''ahaonline.czinfo.cz,onetv.cz##[href*="&token="][target="_blank"]''',
'''ahaonline.czinfo.cz,onetv.cz##a[href^="//api.mgid.com/"]''',
'''ahaonline.czinfo.cz,onetv.cz##div[style*='background-image: url("https://www.']''',
'''ahaonline.czinfo.cz,onetv.cz##.ad-skycrapper''',
'''ahaonline.czinfo.cz,onetv.cz,kinobox.cz##[id*="Adform"]''',
'''ahaonline.czinfo.cz,onetv.cz##div[style*="background-image"][style*="branding"]''',
'''ahaonline.czinfo.cz,onetv.cz##.article-advertisement''',
'''ahaonline.czinfo.cz,onetv.cz##div[id^="cnc-"][class^="cnc-"]''',
'''ahaonline.czinfo.cz,onetv.cz##div[class\$="-banner"]''',
'''ahaonline.cz,info.cz,iprima.cz,kinobox.cz,kupi.cz,nasepenize.cz,novinky.cz,onetv.cz,sport.cz,super.cz##div[id\$="horiz"]''',
'''ahaonline.cz,info.cz,iprima.cz,kinobox.cz,kupi.cz,nasepenize.cz,novinky.cz,onetv.cz,sport.cz,super.cz##iframe[src*=" javascript: window"]''',
'''ahaonline.cz,info.cz,iprima.cz,kinobox.cz,kupi.cz,nasepenize.cz,novinky.cz,onetv.cz,sport.cz,super.cz##.pe-banner''',
'''ahaonline.cz,info.cz,iprima.cz,kinobox.cz,kupi.cz,nasepenize.cz,novinky.cz,onetv.cz,sport.cz,super.cz##.advert''',
'''ahaonline.cz,info.cz,iprima.cz,kinobox.cz,kupi.cz,nasepenize.cz,novinky.cz,onetv.cz,sport.cz,super.cz##a[href*="?action=ppl&cid="]''',
'''ahaonline.czinfo.cz,onetv.cz##div[style*="background-image: url("][style*="background-repeat: no-repeat;"]''',
'''ahaonline.cz,info.cz,kinobox.cz,kupi.cz,nasepenize.cz,onetv.cz##a.tracked-event[data-tid]''',
'''ahaonline.cz,info.cz,kinobox.cz,kupi.cz,nasepenize.cz,onetv.cz##a.tracked-event[href*="&tcid="]''',
'''ahaonline.cz,info.cz,kinobox.cz,kupi.cz,nasepenize.cz,novinky.cz,onetv.cz,sport.cz,super.cz###ads-leader, #ads-leader-board''',
'''ahaonline.cz,info.cz,kinobox.cz,kupi.cz,nasepenize.cz,novinky.cz,onetv.cz,sport.cz,super.cz##.foto-iframe-ads''',
'''ahaonline.czinfo.cz,onetv.cz#?#div:-abp-has(>small:-abp-contains(Reklama))''',
'''ahaonline.czinfo.cz,onetv.cz,novinky.cz,kupi.cz,sport.cz,super.cz,horoskopy.cz,kinobox.cz,nasepenize.cz,fights.cz##a[href*="?adurl="]''',
'''ahaonline.czinfo.cz,onetv.cz,novinky.cz,kupi.cz,sport.cz,super.cz,horoskopy.cz,kinobox.cz,nasepenize.cz,fights.cz##a[href*="mondor_hopToSeti"]''',
'''||d49-a.sdn.cz^\$image,domain=ahaonline.cz|info.cz|iprima.cz|kinobox.cz|kupi.cz|lidovky.cz|nasepenize.cz|novinky.cz|onetv.cz|sport.cz|super.cz''',
'''||userscontent.com^\$image,domain=ahaonline.cz|info.cz|iprima.cz|kinobox.cz|kupi.cz|lidovky.cz|nasepenize.cz|novinky.cz|onetv.cz|sport.cz|super.cz''',
'''novinky.cz#\$#hide-if-matches-xpath '//div[@id][contains(@style, "max-width: 100%;")]//iframe[@style]/ancestor::div[@style]''',
'''novinky.cz#\$#hide-if-matches-xpath '//a[@href][@title]/div[@class][@style]/parent::a/ancestor-or-self::div[2]''',
'''horoskopy.cz,seznamzpravy.cz#\$#hide-if-matches-xpath '//iframe[@src][@id]/parent::div[@class]/ancestor-or-self::div[@class][1][not(starts-with(@class,"twitter"))]''',
'''novinky.cz#\$#hide-if-matches-xpath './/div[@style]/div[contains(@style,"position:relative")][@style]/div[@style]/iframe[contains(@style,"display")]/parent::div[@class][@style]/ancestor::div[@class and @style]''',
'''novinky.cz#\$#hide-if-matches-xpath './/div[@class="tpl-king-bottom-content"]//h3[@class]/a[@target="_top"]/ancestor::article[contains(@class,"advert")]/parent::div[1]'; hide-if-matches-xpath '//div[@id][@style]//div[@*="ad-content"]//iframe[@style]/ancestor::div[@*="mol-advert" and @*="RENDERED"][@style]'; hide-if-matches-xpath './/div[@class]/span[text()][@*="atm-label"]/following::a[@target]/ancestor::article[@*="advert-item"]'; hide-if-matches-xpath './/div[@class][@style]/div[@style]//iframe[@width][@style]/ancestor::div[@*="RENDERED" or @*="mol-advert"]''',
'''seznamzpravy.cz,sport.cz#\$#hide-if-matches-xpath '//div[@class]/div[@*="mol-advert"]''',
'''novinky.cz#\$#hide-if-matches-xpath '//div[@class]/div/p[.="Reklâma"]/parent::div[@class][@style]'; json-prune hlolijkmkhmkkgginioo;''',
'''! #CV-780''',
'''.cz/*,,*,|\$xmlhttprequest,domain=ahaonline.cz|info.cz|onetv.cz''',
'''=autapay/*,|\$xmlhttprequest,domain=ahaonline.cz|info.cz|onetv.cz''',
'''play/safety=^\$xmlhttprequest,domain=ahaonline.cz|info.cz|onetv.cz''',
'''miniplayer/safety=^\$xmlhttprequest,domain=ahaonline.cz|info.cz|onetv.cz''',
'''=miniplayer/\$xmlhttprequest,domain=ahaonline.cz|info.cz|onetv.cz''',
''',e8o,\$xmlhttprequest,domain=ahaonline.cz|info.cz|onetv.cz''',
'''=Ostatni\$xmlhttprequest,domain=ahaonline.cz|info.cz|onetv.cz''',
'''=Pare-toll\$xmlhttprequest,domain=ahaonline.cz|info.cz|onetv.cz''',
'''=Busroll-\$xmlhttprequest,domain=ahaonline.cz|info.cz|onetv.cz''',
'''=Paretol-\$xmlhttprequest,domain=ahaonline.cz|info.cz|onetv.cz''',
'''=Qa-retoll\$xmlhttprequest,domain=ahaonline.cz|info.cz|onetv.cz''',
'''/poho0ze5nci=\$xmlhttprequest,domain=ahaonline.cz|info.cz|onetv.cz''',
'''/naChotina=\$xmlhttprequest,domain=ahaonline.cz|info.cz|onetv.cz''',
'''/elLOeonora=\$xmlhttprequest,script,domain=ahaonline.cz|info.cz|onetv.cz''',
'''/past.js|\$script,domain=www.ahaonline.cz|info.cz|onetv.cz''',
'''/pasta.js|\$script,domain=ahaonline.cz|info.cz|onetv.cz''',
'''&ADFAssetID=\$media,domain=www.ahaonline.cz|info.cz|onetv.cz|iprima.cz''',
'''||videos-fms.jwpsrv.com/*/content/conversions/*.mp4|\$media,domain=ahaonline.cz|info.cz|onetv.cz''',
'''||jwpsrv.com/content/conversions/*/videos/*.mp4?token=\$media,domain=ahaonline.cz|info.cz|onetv.cz''',
'''?bv=0&autoScaleBox=\$media,domain=ahaonline.cz|info.cz|onetv.cz''',
'''=Postroll\$xmlhttprequest,domain=ahaonline.cz|info.cz|onetv.cz''',
'''=Preroll\$xmlhttprequest,domain=ahaonline.cz|info.cz|onetv.cz''',
'''=Paretoll\$xmlhttprequest,domain=ahaonline.cz|info.cz|onetv.cz''',
'''/fal854heat^\$xmlhttprequest,domain=ahaonline.cz|info.cz|onetv.cz''',
'''hlouhopAes=no5\$xmlhttprequest,domain=ahaonline.cz|info.cz|onetv.cz''',
'''/ledo2vnyce=\$xmlhttprequest,domain=ahaonline.cz|info.cz|onetv.cz''',
'''/doubleclick_dmm^*/file.mp4\$media,domain=ahaonline.cz|info.cz|onetv.cz|iprima.cz''',
'''novinky.cz,super.cz,sport.cz##[class*="ClickThrough"]''',
'''preroll\$xmlhttprequest,domain=iprima.cz''',
'''midroll\$xmlhttprequest,domain=iprima.cz''',
'''postroll\$xmlhttprequest,domain=iprima.cz''',
'''iprima.cz##.vjs-ad-link, .vjs-ad-clickthru''',
'''! #CV-764''',
'''clanky.seznam.cz,search.seznam.cz##.Result.Result--organic > :not(.Result-contentContainer):not(.Result-ico):not(.Result-title)''',
'''clanky.seznam.cz,search.seznam.cz##.Result-ico:not([class="Result-ico"])''',
'''clanky.seznam.cz,search.seznam.cz##.Result.Result--organic > .Result-ico:not([class="Result-ico"]) + .Result-contentContainer''',
'''clanky.seznam.cz,search.seznam.cz#?#:-abp-has(> .Result--organic .Result-title-link:not([class="Result-title-link"]))''',
'''clanky.seznam.cz,search.seznam.cz#?#.Result:-abp-has(.Result--organic [class^="Result-contentContainer _"])''',
'''www.seznam.cz#\$#hide-if-matches-xpath './/div[@class="banner-wrapper"]/a[contains(@href,"ad_url")]/div/img/ancestor::div[@id="page"]''',
'''www.seznam.cz#\$#hide-if-matches-xpath './/a[contains(@href,"ad-buttonem")]/ancestor::div[contains(@class,"gadget")]/parent::div[1]''',
'''www.seznam.cz#\$#hide-if-matches-xpath './/a[@href][@target="_blank"][contains(@class,"atm-link--styled")]/following::div[contains(@style,"position:relative;")]/ancestor::div[contains(@style,"flex")]/ancestor::div[@class][2]''',
'''www.seznam.cz#\$#hide-if-matches-xpath './/a[@href][@target="_blank"][contains(@class,"atm-link--styled")]/ancestor-or-self::div[contains(@class,"mol-json-ssp-advert")]/parent::div[contains(@class,"mol-content-card")][1]''',
'''www.seznam.cz#\$#hide-if-matches-xpath './/iframe[@class][@style][@src]/ancestor::div[contains(@style,"position:relative;")]/preceding::div[@id][contains(@style,"max-width: 100%;")][contains(@id,"reload")]/parent::div[@class][1]''',
'''www.seznam.cz#\$#hide-if-matches-xpath './/div[contains(@class,"mol-json-carousel-advert")]/ancestor::div[contains(@class,"atm-feed-card")]/parent::div[@id]''',
'''www.seznam.cz#\$#hide-if-matches-xpath './/div[contains(@class,"atm-advert")]/ancestor::div[contains(@class,"atm-closeable-post")]/ancestor::div[2]''',
'''www.seznam.cz#\$#hide-if-matches-xpath './/div[contains(@class,"gadget-container")]/div[@id and @class]/div[@*="animated-height"]//span[text()]/following-sibling::a[contains(text(),"reklamu")]//following::div[@*="gadget__content"]//div[@class and @style]/ancestor::div[7][@class]/ancestor::div[contains(@class,"gadget-container")]'; hide-if-matches-xpath './/div[starts-with(@class,"d-flex")]/div[contains(@class,"flex-column")]/div[@class and @style]//div[2]/div[@class and,
  //@style]/parent::div/ancestor-or-self::div[contains(@style,"flex-basis:")]'; hide-if-matches-xpath './/div[@*="mainFeed"]//div[@class="overflow-hidden"]/div[contains(@class,"atm-text-placeholder")]/parent::div[@class][1]/ancestor::div[3]/parent::div[@class and @*]/ancestor::li[@data-analytics-first-item]';''',
'''search.seznam.cz#\$#hide-if-matches-xpath './/div/h3[contains(@class,"bd037d")]/a[@data-dot-data]/ancestor::div[@data-e-b-n]''',
'''search.seznam.cz#\$#hide-if-matches-xpath './/picture[@class]/img[contains(@src,"https://d25-a.sdn.cz")]/ancestor::div[contains(@style,"margin-left:")]/ancestor::div[@data-dot-data]''',
'''search.seznam.cz#\$#hide-if-matches-xpath './/picture[@class]/img[contains(@src,"https://d25-a.sdn.cz")]/ancestor::div[contains(@class,"SuperCarousel")]/ancestor::div[@data-e-b-n]''',
'''search.seznam.cz#\$#hide-if-matches-xpath './/picture[@class]/img[contains(@src,"https://d25-a.sdn.cz")]/ancestor::div[@data-e-b-n][@data-n-id]/parent::div[@class][1]''',
'''||seznam.cz/*/static/*/*?nocache=1^\$domain=www.seznam.cz''',
'''||seznam.cz/*/*/js/*?nocache=1^\$domain=www.seznam.cz''',
'''www.seznam.cz#\$#cookie-remover pubmatic''',
'''www.seznam.cz#\$#cookie-remover adform''',
'''www.seznam.cz#\$#override-property-read sssp noopFunc''',
'''! MISC''',
'''zoznam.sk#\$#hide-if-matches-xpath './/div[contains(text(),"Reklama")]/preceding-sibling::div[@class][2]/ancestor::*[3]''',
'''zoznam.sk#\$#hide-if-matches-xpath './/div[@class]/iframe[@id][@title][string-length(@src) > 90]/ancestor::div[1]''',
'''info.cz,lupa.cz,hnonline.sk#\$#abort-current-inline-script Math.random adb''',
'''expres.cz#\$#json-override ads ''''',
'''expres.cz,tiscali.cz,osobnosti.cz#\$#prevent-listener beforeunload (); cookie-remover /^_?adb/;''',
'''expres.cz,idnes.cz#\$#override-property-read pxReady null''',
'''blesk.cz,expres.cz,idnes.cz#\$#abort-on-property-read''',
'''blesk.cz,expres.cz,idnes.cz#\$#cookie-remover /^adb\$|adb\.key|^[a-z]{5,11}\$/''',
'''auto.cz,autorevue.cz,maminka.cz,reflex.cz,blesk.cz,dama.cz,e15.cz,mojezdravi.cz,zeny.cz,zive.cz##.inserted_rtb''',
'''auto.cz,autorevue.cz,maminka.cz,reflex.cz,blesk.cz,dama.cz,e15.cz,mojezdravi.cz,zeny.cz,zive.cz##[id^="ad-"]''',
'''auto.cz,autorevue.cz,maminka.cz,reflex.cz,blesk.cz,dama.cz,e15.cz,mojezdravi.cz,zeny.cz,zive.cz##[data-track-ad]''',
'''auto.cz,autorevue.cz,maminka.cz,reflex.cz,blesk.cz,dama.cz,e15.cz,mojezdravi.cz,zeny.cz,zive.cz##leaderBoard''',
'''auto.cz,autorevue.cz,maminka.cz,reflex.cz,blesk.cz,dama.cz,e15.cz,mojezdravi.cz,zeny.cz,zive.cz##.movingAd''',
'''auto.cz,autorevue.cz,maminka.cz,reflex.cz,blesk.cz,dama.cz,e15.cz,mojezdravi.cz,zeny.cz,zive.cz###brandingCreativeWrapper''',
'''auto.cz,autorevue.cz,maminka.cz,reflex.cz,blesk.cz,dama.cz,e15.cz,mojezdravi.cz,zeny.cz,zive.cz##[data-google-container-id], .is_stuck''',
'''auto.cz,autorevue.cz,maminka.cz,reflex.cz,blesk.cz,dama.cz,e15.cz,mojezdravi.cz,zeny.cz,zive.cz##a[href*=";adfibeg="]''',
'''auto.cz,autorevue.cz,maminka.cz,reflex.cz,blesk.cz,dama.cz,e15.cz,mojezdravi.cz,zeny.cz,zive.cz#?#div:-abp-has(>[class\$="selfpromo"])''',
'''auto.cz,autorevue.cz,maminka.cz,reflex.cz,blesk.cz,dama.cz,e15.cz,mojezdravi.cz,zeny.cz,zive.cz##[class^="stickyContentBottom_"]''',
'''auto.cz,autorevue.cz,maminka.cz,reflex.cz,blesk.cz,dama.cz,e15.cz,mojezdravi.cz,zeny.cz,zive.cz##.ad__in''',
'''auto.cz,autorevue.cz,maminka.cz,reflex.cz,blesk.cz,dama.cz,e15.cz,mojezdravi.cz,zeny.cz,zive.cz##.ad-skywrapper''',
'''auto.cz,autorevue.cz,maminka.cz,reflex.cz,blesk.cz,dama.cz,e15.cz,mojezdravi.cz,zeny.cz,zive.cz##iframe[id^="iframeWrapper-"]''',
'''auto.cz,autorevue.cz,maminka.cz,reflex.cz,blesk.cz,dama.cz,e15.cz,mojezdravi.cz,zeny.cz,zive.cz##[class^="ad "]''',
'''auto.cz,autorevue.cz,maminka.cz,reflex.cz,blesk.cz,dama.cz,e15.cz,mojezdravi.cz,zeny.cz,zive.cz##a[href*="Banner"]''',
'''auto.cz,autorevue.cz,maminka.cz,reflex.cz,blesk.cz,dama.cz,e15.cz,mojezdravi.cz,zeny.cz,zive.cz##a[href*="pubsrcid="]''',
'''auto.cz,autorevue.cz,maminka.cz,reflex.cz,blesk.cz,dama.cz,e15.cz,mojezdravi.cz,zeny.cz,zive.cz##.ads''',
'''auto.cz,autorevue.cz,maminka.cz,reflex.cz,blesk.cz,dama.cz,e15.cz,mojezdravi.cz,zeny.cz,zive.cz##a[href*="banner"]''',
'''auto.cz,autorevue.cz,maminka.cz,reflex.cz,blesk.cz,dama.cz,e15.cz,mojezdravi.cz,zeny.cz,zive.cz##.sticky-content''',
'''auto.cz,autorevue.cz,maminka.cz,reflex.cz,blesk.cz,dama.cz,e15.cz,mojezdravi.cz,zeny.cz,zive.cz##.SC_TBlock''',
'''auto.cz,autorevue.cz,maminka.cz,reflex.cz,blesk.cz,dama.cz,e15.cz,mojezdravi.cz,zeny.cz,zive.cz###leader_board''',
'''auto.cz,autorevue.cz,maminka.cz,reflex.cz,blesk.cz,dama.cz,e15.cz,mojezdravi.cz,zeny.cz,zive.cz##.ad-skyscrapper''',
'''auto.cz,autorevue.cz,maminka.cz,reflex.cz,blesk.cz,dama.cz,e15.cz,mojezdravi.cz,zeny.cz,zive.cz###Moitor-1''',
'''auto.cz,autorevue.cz,maminka.cz,reflex.cz,blesk.cz,dama.cz,e15.cz,mojezdravi.cz,zeny.cz,zive.cz##div[style*="_banner_branding_cnc_"]''',
'''auto.cz,autorevue.cz,maminka.cz,reflex.cz,blesk.cz,dama.cz,e15.cz,mojezdravi.cz,zeny.cz,zive.cz###banner_id''',
'''auto.cz,autorevue.cz,maminka.cz,reflex.cz,blesk.cz,dama.cz,e15.cz,mojezdravi.cz,zeny.cz,zive.cz###banner''',
'''auto.cz,autorevue.cz,maminka.cz,reflex.cz,blesk.cz,dama.cz,e15.cz,mojezdravi.cz,zeny.cz,zive.cz###creativelink''',
'''auto.cz,autorevue.cz,maminka.cz,reflex.cz,blesk.cz,dama.cz,e15.cz,mojezdravi.cz,zeny.cz,zive.cz##.rollWrapper''',
'''auto.cz,autorevue.cz,maminka.cz,reflex.cz,blesk.cz,dama.cz,e15.cz,mojezdravi.cz,zeny.cz,zive.cz###ValRageBottom''',
'''auto.cz,autorevue.cz,maminka.cz,reflex.cz,blesk.cz,dama.cz,e15.cz,mojezdravi.cz,zeny.cz,zive.cz##a[href*="branding"]''',
'''auto.cz,autorevue.cz,maminka.cz,reflex.cz,blesk.cz,dama.cz,e15.cz,mojezdravi.cz,zeny.cz,zive.cz,www.idnes.cz,expres.cz#?#div:-abp-has(>a[href\$="/personalizovana-reklama/"])''',
'''blesk.cz##.gam-wrapper''',
'''expres.cz,idnes.cz##div[data-redistribute="ad"]''',
'''idnes.cz###foto-reklama''',
'''/partnerJsApi/v3?previousZHashes=&hash=*&clbk=sklik\$script,domain=auto.cz|autorevue.cz|maminka.cz|reflex.cz|blesk.cz|dama.cz|e15.cz|mojezdravi.cz|zeny.cz|zive.cz''',
'''&uid=ssp-\$script,domain=auto.cz|autorevue.cz|maminka.cz|reflex.cz|blesk.cz|dama.cz|e15.cz|mojezdravi.cz|zeny.cz|zive.cz''',
'''.cz/*/js/a.js|\$script,domain=auto.cz|autorevue.cz|maminka.cz|reflex.cz|blesk.cz|dama.cz|e15.cz|mojezdravi.cz|zeny.cz|zive.cz''',
'''||cdn.user-api.com^\$domain=auto.cz|autorevue.cz|maminka.cz|reflex.cz|blesk.cz|dama.cz|e15.cz|mojezdravi.cz|zeny.cz|zive.cz''',
'''||cnc.cdn.dopc.cz.^\$script,domain=blesk.cz''',
'''||cnc.cdn.dopc.cz^*?format=js\$script,domain=auto.cz|autorevue.cz|maminka.cz|reflex.cz|blesk.cz|dama.cz|e15.cz|mojezdravi.cz|zeny.cz|zive.cz''',
'''/scripts^\$subdocument,domain=auto.cz|autorevue.cz|maminka.cz|reflex.cz|blesk.cz|dama.cz|e15.cz|mojezdravi.cz|zeny.cz|zive.cz''',
'''.cz/*/area=adblock\$script,popup,domain=auto.cz|autorevue.cz|maminka.cz|reflex.cz|blesk.cz|dama.cz|e15.cz|mojezdravi.cz|zeny.cz|zive.cz''',
'''&pssp1=\$xmlhttprequest,domain=auto.cz|autorevue.cz|maminka.cz|reflex.cz|blesk.cz|dama.cz|e15.cz|mojezdravi.cz|zeny.cz|zive.cz|www.idnes.cz|expres.cz''',
'''&cmpState=\$script,domain=auto.cz|autorevue.cz|maminka.cz|reflex.cz|blesk.cz|dama.cz|e15.cz|mojezdravi.cz|zeny.cz|zive.cz|expres.cz|www.idnes.cz''',
'''&ifr=0|\$script,domain=www.idnes.cz|expres.cz|auto.cz|autorevue.cz|maminka.cz|reflex.cz|blesk.cz|dama.cz|e15.cz|mojezdravi.cz|zeny.cz|zive.cz''',
'''=js&lst=\$script,domain=www.idnes.cz|expres.cz|auto.cz|autorevue.cz|maminka.cz|reflex.cz|blesk.cz|dama.cz|e15.cz|mojezdravi.cz|zeny.cz|zive.cz|tiscali.cz|kinobox.cz|osobnosti.cz|karaoketexty.cz|nasepenize.cz|fights.cz|novinky.cz|super.cz|sport.cz|kupi.cz|horoskopy.cz''',
'''/tigatage:\$script,domain=www.idnes.cz|expres.cz|auto.cz|autorevue.cz|maminka.cz|reflex.cz|dama.cz|e15.cz|mojezdravi.cz|zeny.cz|zive.cz|tiscali.cz|kinobox.cz|osobnosti.cz|karaoketexty.cz|nasepenize.cz|fights.cz|novinky.cz|super.cz|sport.cz|kupi.cz|horoskopy.cz''',
'''||w-cached.cncenter.cz/js/cnc-ads-controller.\$script,domain=blesk.cz|reflex.cz|zive.cz|auto.cz|e15.cz|autorevue.cz|dama.cz|maminka.cz|mojezdravi.cz|zeny.cz''',
'''client=ca-pub-\$subdocument,domain=www.idnes.cz|expres.cz|auto.cz|autorevue.cz|maminka.cz|reflex.cz|blesk.cz|dama.cz|e15.cz|mojezdravi.cz|zeny.cz|zive.cz''',
'''reflex.cz###gl-nat''',
'''e15.cz##.mys-wrapper''',
'''blesk.cz##.banner-ifortuna''',
'''blesk.cz##article[data-track-element-id*="prPremium"]''',
'''blesk.cz##div[data-track-element-id^="prStandardZpravy"]''',
'''blesk.cz###px2-wall-wrap''',
'''blesk.cz###stickyfloatLeftEmptySpaceCheckLeft''',
'''blesk.cz##div[class^="sticky-wrapper"]''',
'''expres.cz,idnes.cz##[class^="r-main"]''',
'''expres.cz#\$#hide-if-contains-visible-text /[a-zA-Z]/ '*[class][id]' span[id][data-rsize]''',
'''dama.cz##[class*="ads-"]''',
'''zeny.cz,auto.cz##[data-track-ad]''',
'''reflex.cz##img[title\$=".cz"][src^="https://www.reflex.cz/"]''',
'''auto.cz##.halfpageAd, [class*="wrapperH-prapper"], [class*="billboard-bottom"], img[width='970'][height="310"], [data-io-article-url] a[target='_top'], video[id^="video-"][preload="auto"][webkit-playsinline="webkit-playsinline"], [class*="ads-leader"], #KoqisAoAce''',
'''www.blesk.cz##[class*="-wrapperf-prapper"], [class*="pikyTentBot_"], #stickyBottomRightAbsolute, [class="lol__out"], img[width='970'][height="310"], a[style*="blewid: 970px; height: 310px"], div[id*="-hor"]''',
'''autorevue.cz##.bx-sky, .bx-rectangle-article''',
'''maminka.cz##div[class*="bx-sky "]''',
'''dama.cz##div[class^="sky-wrap"]''',
'''maminka.cz,blesk.cz,reflex.cz,e15.cz##a[class*="-combined"]''',
'''blesk.cz#\$#abort-current-inline-script  adbDetect; prevent-listener beforeunload (); override-property-read adBlockerFound undefined;''',
'''tiscali.cz,osobnosti.cz,karaoketexty.cz###stickyBanner''',
'''tiscali.cz##a[target="_blank"][href*="tiscali.cz"]>img[src*="tiscali.cz"]''',
'''tiscali.cz,osobnosti.cz,karaoketexty.cz##.btitle-right''',
'''tiscali.cz,osobnosti.cz,karaoketexty.cz##a[href*="IdBnrP="][href*="IdCamp="]''',
'''tiscali.cz,osobnosti.cz,karaoketexty.cz##[id^="pxBanner"]''',
'''tiscali.cz,osobnosti.cz,karaoketexty.cz###clickLayer''',
'''karaoketexty.cz###stickyWrap''',
'''karaoketexty.cz##.ad_large_square''',
'''tiscali.cz,osobnosti.cz,karaoketexty.cz##a[target="_blank"]>img[class*="-click-"]''',
'''tiscali.cz,osobnosti.cz,karaoketexty.cz##.sticky[stickystop]''',
'''tiscali.cz,osobnosti.cz,karaoketexty.cz##[class\$=" sticky"]''',
'''karaoketexty.cz##[class\$="_rightcolumn"]''',
'''karaoketexty.cz###sky_right_col''',
'''osobnosti.cz##.hide-screenbot''',
'''tiscali.cz,osobnosti.cz,karaoketexty.cz##div[class\$="-rightcJ"]''',
'''tiscali.cz,osobnosti.cz,karaoketexty.cz##.SC_TBlock''',
'''tiscali.cz,osobnosti.cz,karaoketexty.cz##.pe-link''',
'''tiscali.cz,osobnosti.cz,karaoketexty.cz##.wrap-advert''',
'''tiscali.cz,osobnosti.cz,karaoketexty.cz##.quaquaquakva''',
'''tiscali.cz,osobnosti.cz,karaoketexty.cz##[href*=";cdata="]''',
'''tiscali.cz##.bs-hp''',
'''tiscali.cz###desktop-square-top, #desktop-leader-top, .desktop-square-top, .desktop-leader-top''',
'''tiscali.cz##[class*="-ld-top"]''',
'''tiscali.cz,osobnosti.cz,karaoketexty.cz##[id*="tmAdVideo"], [class=" pe-banner"]''',
'''expres.cz##.barMan''',
'''auto.cz,autorevue.cz,maminka.cz,reflex.cz,blesk.cz,dama.cz,e15.cz,mojezdravi.cz,zeny.cz,zive.cz,expres.cz##a[href*="verdsi="][href*="&ip="]''',
'''auto.cz,autorevue.cz,maminka.cz,reflex.cz,blesk.cz,dama.cz,e15.cz,mojezdravi.cz,zeny.cz,zive.cz,expres.cz##[href*="&token="][target="_blank"]''',
'''auto.cz,autorevue.cz,maminka.cz,reflex.cz,blesk.cz,dama.cz,e15.cz,mojezdravi.cz,zeny.cz,zive.cz,expres.cz##a[href^="//api.mgid.com/"]''',
'''auto.cz,autorevue.cz,maminka.cz,reflex.cz,blesk.cz,dama.cz,e15.cz,mojezdravi.cz,zeny.cz,zive.cz##div[style*='background-image: url("https://www.']''',
'''auto.cz,autorevue.cz,maminka.cz,reflex.cz,blesk.cz,dama.cz,e15.cz,mojezdravi.cz,zeny.cz,zive.cz##.ad-skycrapper''',
'''auto.cz,autorevue.cz,maminka.cz,reflex.cz,blesk.cz,dama.cz,e15.cz,mojezdravi.cz,zeny.cz,zive.cz,osobnosti.cz,tiscali.cz,karaoketexty.cz##[id*="Adform"]''',
'''auto.cz,autorevue.cz,maminka.cz,reflex.cz,blesk.cz,dama.cz,e15.cz,mojezdravi.cz,zeny.cz,zive.cz##div[style*="background-image"][style*="branding"]''',
'''auto.cz,autorevue.cz,maminka.cz,reflex.cz,blesk.cz,dama.cz,e15.cz,mojezdravi.cz,zeny.cz,zive.cz##.article-advertisement''',
'''auto.cz,autorevue.cz,maminka.cz,reflex.cz,blesk.cz,dama.cz,e15.cz,mojezdravi.cz,zeny.cz,zive.cz##div[id^="cnc-"][class^="cnc-"]''',
'''auto.cz,autorevue.cz,maminka.cz,reflex.cz,blesk.cz,dama.cz,e15.cz,mojezdravi.cz,zeny.cz,zive.cz,karaoketexty.cz##div[class\$="-banner"]''',
'''auto.cz,autorevue.cz,blesk.cz,dama.cz,e15.cz,expres.cz,karaoketexty.cz,maminka.cz,mojezdravi.cz,osobnosti.cz,reflex.cz,tiscali.cz,zeny.cz,zive.cz##div[id\$="horiz"]''',
'''auto.cz,autorevue.cz,blesk.cz,dama.cz,e15.cz,expres.cz,karaoketexty.cz,maminka.cz,mojezdravi.cz,osobnosti.cz,reflex.cz,tiscali.cz,zeny.cz,zive.cz##iframe[src*=" javascript: window"]''',
'''auto.cz,autorevue.cz,blesk.cz,dama.cz,e15.cz,expres.cz,karaoketexty.cz,maminka.cz,mojezdravi.cz,osobnosti.cz,reflex.cz,tiscali.cz,zeny.cz,zive.cz##.pe-banner''',
'''auto.cz,autorevue.cz,blesk.cz,dama.cz,e15.cz,expres.cz,karaoketexty.cz,maminka.cz,mojezdravi.cz,osobnosti.cz,reflex.cz,tiscali.cz,zeny.cz,zive.cz##.advert''',
'''auto.cz,autorevue.cz,blesk.cz,dama.cz,e15.cz,expres.cz,karaoketexty.cz,maminka.cz,mojezdravi.cz,osobnosti.cz,reflex.cz,tiscali.cz,zeny.cz,zive.cz##a[href*="?action=ppl&cid="]''',
'''auto.cz,autorevue.cz,maminka.cz,reflex.cz,blesk.cz,dama.cz,e15.cz,mojezdravi.cz,zeny.cz,zive.cz,expres.cz##div[style*="background-image: url("][style*="background-repeat: no-repeat;"]''',
'''auto.cz,autorevue.cz,blesk.cz,dama.cz,e15.cz,expres.cz,karaoketexty.cz,maminka.cz,mojezdravi.cz,osobnosti.cz,reflex.cz,tiscali.cz,zeny.cz,zive.cz##a.tracked-event[data-tid]''',
'''auto.cz,autorevue.cz,blesk.cz,dama.cz,e15.cz,expres.cz,karaoketexty.cz,maminka.cz,mojezdravi.cz,osobnosti.cz,reflex.cz,tiscali.cz,zeny.cz,zive.cz##a.tracked-event[href*="&tcid="]''',
'''auto.cz,autorevue.cz,blesk.cz,dama.cz,e15.cz,expres.cz,karaoketexty.cz,maminka.cz,mojezdravi.cz,osobnosti.cz,reflex.cz,tiscali.cz,zeny.cz,zive.cz###ads-leader, #ads-leader-board''',
'''auto.cz,autorevue.cz,blesk.cz,dama.cz,e15.cz,expres.cz,karaoketexty.cz,maminka.cz,mojezdravi.cz,osobnosti.cz,reflex.cz,tiscali.cz,zeny.cz,zive.cz##.foto-iframe-ads''',
'''auto.cz,autorevue.cz,maminka.cz,reflex.cz,blesk.cz,dama.cz,e15.cz,mojezdravi.cz,zeny.cz,zive.cz,expres.cz#?#div:-abp-has(>small:-abp-contains(Reklama))''',
'''auto.cz,autorevue.cz,maminka.cz,reflex.cz,blesk.cz,dama.cz,e15.cz,mojezdravi.cz,zeny.cz,zive.cz,tiscali.cz,osobnosti.cz,karaoketexty.cz##a[href*="?adurl="]''',
'''auto.cz,autorevue.cz,maminka.cz,reflex.cz,blesk.cz,dama.cz,e15.cz,mojezdravi.cz,zeny.cz,zive.cz,tiscali.cz,osobnosti.cz,karaoketexty.cz##a[href*="mondor_hopToSeti"]''',
'''||d49-a.sdn.cz^\$image,domain=auto.cz|autorevue.cz|blesk.cz|dama.cz|e15.cz|expres.cz|karaoketexty.cz|kinobox.cz|kupi.cz|lidovky.cz|maminka.cz|mojezdravi.cz|nasepenize.cz|novinky.cz|osobnosti.cz|reflex.cz|sport.cz|super.cz|tiscali.cz|zeny.cz|zive.cz''',
'''||userscontent.com^\$image,domain=auto.cz|autorevue.cz|blesk.cz|dama.cz|e15.cz|expres.cz|karaoketexty.cz|kinobox.cz|kupi.cz|lidovky.cz|maminka.cz|mojezdravi.cz|nasepenize.cz|novinky.cz|osobnosti.cz|reflex.cz|sport.cz|super.cz|tiscali.cz|zeny.cz|zive.cz''',
'''karaoketexty.cz#\$#hide-if-matches-xpath './/a[string-length(@href) >120][@target="_blank"]/ancestor-or-self::a[@href]''',
'''||www.karaoketexty.cz/*/*.png\$domain=karaoketexty.cz,rewrite=abp-resource:2x2-transparent-png''',
'''||www.karaoketexty.cz/*/*.jpg\$domain=karaoketexty.cz,rewrite=abp-resource:2x2-transparent-png''',
'''@@||karaoketexty.cz/img/*.png\$image,domain=karaoketexty.cz''',
'''@@||karaoketexty.cz/img/*.jpg\$image,domain=karaoketexty.cz''',
'''?client=ca-pub-\$script,domain=karaoketexty.cz''',
'''.cz/*,*,|\$xmlhttprequest,domain=auto.cz|autorevue.cz|maminka.cz|reflex.cz|blesk.cz|dama.cz|e15.cz|mojezdravi.cz|zeny.cz|zive.cz''',
'''=autapay/*,|\$xmlhttprequest,domain=auto.cz|autorevue.cz|maminka.cz|reflex.cz|blesk.cz|dama.cz|e15.cz|mojezdravi.cz|zeny.cz|zive.cz''',
'''play/safety=^\$xmlhttprequest,domain=auto.cz|autorevue.cz|maminka.cz|reflex.cz|blesk.cz|dama.cz|e15.cz|mojezdravi.cz|zeny.cz|zive.cz''',
'''miniplayer/safety=^\$xmlhttprequest,domain=auto.cz|autorevue.cz|maminka.cz|reflex.cz|blesk.cz|dama.cz|e15.cz|mojezdravi.cz|zeny.cz|zive.cz''',
'''=miniplayer/\$xmlhttprequest,domain=auto.cz|autorevue.cz|maminka.cz|reflex.cz|blesk.cz|dama.cz|e15.cz|mojezdravi.cz|zeny.cz|zive.cz''',
'''e8o,\$xmlhttprequest,domain=auto.cz|autorevue.cz|maminka.cz|reflex.cz|blesk.cz|dama.cz|e15.cz|mojezdravi.cz|zeny.cz|zive.cz''',
'''=Ostatni\$xmlhttprequest,domain=auto.cz|autorevue.cz|maminka.cz|reflex.cz|blesk.cz|dama.cz|e15.cz|mojezdravi.cz|zeny.cz|zive.cz''',
'''=Pare-toll\$xmlhttprequest,domain=auto.cz|autorevue.cz|maminka.cz|reflex.cz|blesk.cz|dama.cz|e15.cz|mojezdravi.cz|zeny.cz|zive.cz''',
'''=Busroll-\$xmlhttprequest,domain=auto.cz|autorevue.cz|maminka.cz|reflex.cz|blesk.cz|dama.cz|e15.cz|mojezdravi.cz|zeny.cz|zive.cz''',
'''=Paretol-\$xmlhttprequest,domain=auto.cz|autorevue.cz|maminka.cz|reflex.cz|blesk.cz|dama.cz|e15.cz|mojezdravi.cz|zeny.cz|zive.cz''',
'''=Qa-retoll\$xmlhttprequest,domain=auto.cz|autorevue.cz|maminka.cz|reflex.cz|blesk.cz|dama.cz|e15.cz|mojezdravi.cz|zeny.cz|zive.cz''',
'''/poho0ze5nci=\$xmlhttprequest,domain=auto.cz|autorevue.cz|maminka.cz|reflex.cz|blesk.cz|dama.cz|e15.cz|mojezdravi.cz|zeny.cz|zive.cz''',
'''/naChotina=\$xmlhttprequest,domain=auto.cz|autorevue.cz|maminka.cz|reflex.cz|blesk.cz|dama.cz|e15.cz|mojezdravi.cz|zeny.cz|zive.cz''',
'''/elLOeonora=\$xmlhttprequest,script,domain=auto.cz|autorevue.cz|maminka.cz|reflex.cz|blesk.cz|dama.cz|e15.cz|mojezdravi.cz|zeny.cz|zive.cz''',
'''/past.js|\$script,domain=expres.cz|www.idnes.cz|auto.cz|autorevue.cz|maminka.cz|reflex.cz|blesk.cz|dama.cz|e15.cz|mojezdravi.cz|zeny.cz|zive.cz''',
'''/pasta.js|\$script,domain=auto.cz|autorevue.cz|maminka.cz|reflex.cz|blesk.cz|dama.cz|e15.cz|mojezdravi.cz|zeny.cz|zive.cz''',
'''&ADFAssetID=\$media,domain=expres.cz|www.idnes.cz|auto.cz|autorevue.cz|maminka.cz|reflex.cz|blesk.cz|dama.cz|e15.cz|mojezdravi.cz|zeny.cz|zive.cz''',
'''||videos-fms.jwpsrv.com/*/content/conversions/*.mp4|\$media,domain=auto.cz|autorevue.cz|maminka.cz|reflex.cz|blesk.cz|dama.cz|e15.cz|mojezdravi.cz|zeny.cz|zive.cz''',
'''||jwpsrv.com/content/conversions/*/videos/*.mp4?token=\$media,domain=auto.cz|autorevue.cz|maminka.cz|reflex.cz|blesk.cz|dama.cz|e15.cz|mojezdravi.cz|zeny.cz|zive.cz''',
'''?bv=0&autoScaleBox=\$media,domain=auto.cz|autorevue.cz|maminka.cz|reflex.cz|blesk.cz|dama.cz|e15.cz|mojezdravi.cz|zeny.cz|zive.cz''',
'''=Postroll\$xmlhttprequest,domain=auto.cz|autorevue.cz|maminka.cz|reflex.cz|blesk.cz|dama.cz|e15.cz|mojezdravi.cz|zeny.cz|zive.cz''',
'''=Preroll\$xmlhttprequest,domain=auto.cz|autorevue.cz|maminka.cz|reflex.cz|blesk.cz|dama.cz|e15.cz|mojezdravi.cz|zeny.cz|zive.cz''',
'''=Paretoll\$xmlhttprequest,domain=auto.cz|autorevue.cz|maminka.cz|reflex.cz|blesk.cz|dama.cz|e15.cz|mojezdravi.cz|zeny.cz|zive.cz''',
'''/fal854heat^\$xmlhttprequest,domain=auto.cz|autorevue.cz|maminka.cz|reflex.cz|blesk.cz|dama.cz|e15.cz|mojezdravi.cz|zeny.cz|zive.cz''',
'''hlouhopAes=no5\$xmlhttprequest,domain=auto.cz|autorevue.cz|maminka.cz|reflex.cz|blesk.cz|dama.cz|e15.cz|mojezdravi.cz|zeny.cz|zive.cz''',
'''/ledo2vnyce=\$xmlhttprequest,domain=auto.cz|autorevue.cz|maminka.cz|reflex.cz|blesk.cz|dama.cz|e15.cz|mojezdravi.cz|zeny.cz|zive.cz''',
'''/?bn=*&ord=\$xmlhttprequest,script,domain=expres.cz|idnes.cz''',
'''ad0R\$xmlhttprequest,domain=expres.cz|idnes.cz''',
'''/doubleclick_dmm^*/file.mp4\$media,domain=expres.cz|idnes.cz|auto.cz|autorevue.cz|maminka.cz|reflex.cz|blesk.cz|dama.cz|e15.cz|mojezdravi.cz|zeny.cz|zive.cz''',
'''expres.cz,idnes.cz##a[href*="area=preroll_"]''',
'''expres.cz,idnes.cz##a[href*="click?xai="]''',
'''expres.cz,idnes.cz##videoplayer>video[data-io-video-title*="_idnestv_"]''',
'''expres.cz,idnes.cz##a[href*="preroll"]''',
'''idnes.cz,expres.cz##a[href*=";cdata="]''',
'''idnes.cz,expres.cz##a[href*="/supertag=InstreamVideo/"]''',
'''karaoketexty.cz#\$#abort-current-inline-script  adb''',
'''! Popup/Popunder''',
'''dlouha-videa.cz#\$#abort-on-property-read _0x4c29''',
'''! *** abp-filters-anti-cv:dutch.txt ***''',
'''! #CV-660''',
'''ajaxshowtime.com#?#div:-abp-properties(content: "Advertentie";)''',
'''ajaxshowtime.com##div.leaderboard_ad + div''',
'''! *** abp-filters-anti-cv:english.txt ***''',
'''! CV-3560''',
'''groceries.morrisons.com#\$#hide-if-matches-xpath './/div[@data-test="products-page"]//*[starts-with(@data-test, "fop-wrapper")]/div[.//*[contains(text(), "Sponsored")] or @class="outer-header-container" and ./span[@data-test="breadcrumb-text"][contains(text(), "Featured")]]''',
'''! CV-3613''',
'''threenow.co.nz#\$#override-property-read Object.prototype.adConfigId undefined; json-prune 'ad_keys cue_points' 'account_id sources';''',
'''! CV-3435''',
'''marketwatch.com,wsj.com#\$#abort-on-property-write window.__buildAd;''',
'''marketwatch.com#\$#hide-if-contains-visible-text /Advertisement/ 'div[class^="container"]' 'div>span''',
'''! RM-65''',
'''skyscanner.*,tianxun.com#\$#hide-if-matches-xpath './/button[contains(@class,"SponsoredInfoButton_adInfoBtn")]/ancestor-or-self::div[@aria-label]/parent::div[1]''',
'''skyscanner.*,tianxun.com#\$#hide-if-matches-xpath './/button[contains(@class,"SponsoredInfoButton_adInfoBtn")]/ancestor-or-self::a[contains(@href,"sponsored")][@data-testid]/parent::div[1]''',
'''skyscanner.*,tianxun.com#\$#hide-if-matches-xpath './/button[contains(@class,"SponsoredInfoButton_adInfoBtn")]/preceding::div[contains(@class,"ItineraryInlinePlusWrapperHeader_header")][@role="group"][@aria-label]/parent::div[1]''',
'''! RM-61''',
'''@@||woolworths.com.au^\$generichide''',
'''woolworths.com.au#\$#hide-if-contains-visible-text /\s*Promoted\s*/ 'div .ng-star-inserted wc-product-tile' 'wc-product-tile ^^sh^^ div.sponsored-text''',
'''woolworths.com.au#\$#hide-if-contains-visible-text /\s*Promoted\s*/ 'div>wc-product-tile' 'wc-product-tile ^^sh^^ div.sponsored-text''',
'''! CV-1364''',
'''||html-load.com^\$domain=convertcase.net|manta.com|wfmz.com|golf-live.at|eurointegration.com.ua''',
'''convertcase.net,manta.com,wfmz.com,golf-live.at,eurointegration.com.ua#\$#abort-current-inline-script Symbol error-report.com''',
'''! RM-42''',
'''tesco.com#\$#hide-if-contains-visible-text /Sponsored/ ul[id^="list-content"]>li 'div>div>span''',
'''! RM-114''',
'''! sp''',
'''target.com#\$#hide-if-matches-xpath './/p[text()="Sponsored"]/parent::div[@class]/ancestor::div[contains(@data-test,"ProductCardWrapper")][1]''',
'''! #RM-75''',
'''! sp''',
'''bol.com#?#ul[class][data-test="products"] li:-abp-has(span:-abp-contains(/Gesponsord|Sponsorisé/))''',
'''! pp''',
'''bol.com##section[data-group-name^="sponsored-products"]''',
'''! #RM-1''',
'''tripadvisor.com#\$#hide-if-matches-xpath './/a[contains(text(),"Sponsored")][@target="_blank"]/parent::div/ancestor::div[@class][2]''',
'''tripadvisor.com#\$#hide-if-matches-xpath './/span[@class="listItem"]//div[@data-automation]//span[contains(text(),"Sponsored")]/ancestor::span/parent::div[1]''',
'''tripadvisor.com#\$#hide-if-matches-xpath './/div[@id="typeahead_results"]//div[contains(text(),"Sponsored")]/ancestor::a[@href]''',
'''tripadvisor.com#\$#hide-if-matches-xpath './/span[contains(text(),"Sponsored")]/ancestor::a[@target="_blank"]/ancestor::li[@class]''',
'''! HP & BA''',
'''tripadvisor.com#\$#hide-if-matches-xpath './/span[contains(text(), "SPONSORED")]/ancestor-or-self::a[@target="_blank"][@href]/parent::div[1]''',
'''tripadvisor.com#\$#hide-if-matches-xpath './/div/span[contains(text(), "Sponsored")]/ancestor::section[@class][not(@id)]''',
'''tripadvisor.com#\$#hide-if-matches-xpath './/div[@data-curated-shelf-id and .//div[contains(text(), "Sponsored by")]]/self::div[1]''',
'''tripadvisor.com#\$#hide-if-matches-xpath '//div[.//div[contains(text(), "Sponsored by: ")]]/ancestor-or-self::span[1]/parent::div[1]''',
'''tripadvisor.com#\$#hide-if-matches-xpath './/span[contains(text(), "SPONSORED")]/../../../preceding-sibling::div[@data-vjs-player="true"]/parent::div''',
'''tripadvisor.com#\$#hide-if-matches-xpath './/div[@data-test-target="hero-gallery"][../following-sibling::div//div[contains(text(),"Sponsored by")]]/parent::div/parent::div''',
'''tripadvisor.com#\$#hide-if-matches-xpath './/h2[@class][contains(text(),"Sponsored by")]/preceding::div[@data-vjs-player]/parent::div[not(@class)]''',
'''tripadvisor.com##[data-sponsored]''',
'''! RL''',
'''tripadvisor.com,tripadvisor.com.br,tripadvisor.ca,tripadvisor.com.mx,tripadvisor.com.ar,tripadvisor.cl,tripadvisor.co,tripadvisor.com.ve,tripadvisor.co.uk,tripadvisor.it,tripadvisor.es,tripadvisor.de,tripadvisor.fr,tripadvisor.se,tripadvisor.nl,tripadvisor.com.tr,tripadvisor.dk,tripadvisor.at,tripadvisor.com.gr,no.tripadvisor.com,tripadvisor.pt,tripadvisor.ru,tripadvisor.ch,tripadvisor.be,tripadvisor.jp,cn.tripadvisor.com,tripadvisor.in,tripadvisor.com.my,tripadvisor.com.ph,tripadvisor.com.sg,tripadvisor.co.id,tripadvisor.co.kr,th.tripadvisor.com,tripadvisor.com.tw,tripadvisor.com.hk,tripadvisor.co.za,ar.tripadvisor.com,tripadvisor.com.eg,tripadvisor.co.il#\$#hide-if-matches-xpath '././/span[contains(.,"Patrocinado") or contains(.,"Annonce") or contains(.,"Sponsored") or contains (.,"Sponsorizzato") or contains(., "Gesponsert") or contains(.,"Sponsrad") or contains(.,"Gesponsord") or contains(.,"Sponsorlu") or contains(.,"Sponsoreret") or contains(.,"Χορηγία") or contains(.,"Sponset") or contains(.,"Реклама") or contains(.,"スポンサー提供") or contains(.,"赞助商") or contains(.,"Bersponsor") or contains(.,"스폰서") or contains(.,"สปอนเซอร์") or contains(.,"贊助商") or contains(.,"贊助") or contains(.,"مدعوم") or contains(.,"מודעה")]/ancestor::header/ancestor-or-self::div[2]''',
'''tripadvisor.com#\$#hide-if-matches-xpath './/ul[li/picture]/parent::div/following::span[text()="Sponsored"]/ancestor::div[.//picture and .//a[contains(@href, "Restaurant_Review")]/following::ul/li][1]/parent::div/ancestor-or-self::span[1]''',
'''! #RM-85''',
'''! #RM-78''',
'''noon.com#\$#hide-if-matches-xpath './/span[@color][contains(text(),"Sponsored")]/ancestor-or-self::div[@class="componentArea-0"]''',
'''noon.com#\$#hide-if-matches-xpath './/div[@class][contains(text(),"Sponsored")]/ancestor::a[@href][@id]/ancestor-or-self::div[@class="componentArea-0"]''',
'''noon.com#\$#hide-if-matches-xpath './/span[text()="Sponsored"]/preceding::img[contains(@src,"/ads/banner")]/ancestor-or-self::div[contains(@class,"adBannerModule")][@data-qa]/parent::div''',
'''noon.com##div[data-slotid*="hero_banner_"]''',
'''! #RM-68''',
'''cars.com#\$#hide-if-matches-xpath './/spark-badge[@variant="text"]/ancestor-or-self::div[contains(@class,"inventory-ad")]''',
'''cars.com#\$#hide-if-matches-xpath './/span[@class="hero-cta-tag"][contains(text(),"Sponsored")]/preceding::img[@class="sponsored-hero-cta"]/ancestor::a[@aria-describedby][contains(@href,"adclick")]/ancestor-or-self::section[@id="primary-hero"]''',
'''! #CV-1935''',
'''##.jag8CityBio212023''',
'''reddit.com##.jag8CityBio212023''',
'''! #RM-4''',
'''acmemarkets.com,albertsons.com,andronicos.com,balduccis.com,carrsqc.com,haggen.com,jewelosco.com,kingsfoodmarkets.com,pavilions.com,randalls.com,safeway.com,shaws.com,starmarket.com,tomthumb.com,vons.com#\$#hide-if-matches-xpath './/div[contains(text(),"Sponsored")]/parent::div/ancestor::div[contains(@class,"slick-product")][1]'; hide-if-matches-xpath './/div/div[contains(@data-qa,"spnsrd")][text()="Sponsored"]/parent::div/ancestor::div[contains(@class,"placeholder")][1]';''',
'''! #RM-11''',
'''! hp''',
'''ebay.com#\$#hide-if-matches-xpath './/div[@class]/h2[contains(.,"Sponsored")]//ancestor::div[@data-viewdtls][@data-pushed-view="true"]''',
'''! ba''',
'''ebay.*#\$#hide-if-contains-visible-text /Sponsored|Anzeige|Sponsorisé|Sponsorizzato|Sponsorowane|Gesponsord|Patrocinado/ 'div[data-testid="x-pda-placements"]>div>div>div' 'div[data-viewport]>span>span>span>button[aria-expanded="false"]>div[style="min-height:1px"]''',
'''ebay.*#\$#hide-if-contains-visible-text /Sponsored|Anzeige|Sponsorisé|Sponsorizzato|Sponsorowane|Gesponsord|Patrocinado/ 'div[id^="placement"][style^="min-height:144px;"]>div' 'div[data-viewport]>div''',
'''||ir.ebaystatic.com/cr/ads/nuts/berries-with-css-symbol*.js^\$script,domain=ebay.*''',
'''ebay.*#\$#abort-on-property-read window.ebayAdsBerries.render; abort-on-property-read window.berries''',
'''ebay.com#\$#hide-if-contains-visible-text /Sponsored/ 'div[data-testid="x-pda-placements"]>div>div>div' 'div[data-viewport]>span>div>div ^^sh^^ *''',
'''ebay.com#\$#hide-if-contains-visible-text /Sponsored/ 'div[id*="placement_"]>div' 'div[data-viewport]>span>div[aria-labelledby]>div[aria-hidden]''',
'''! cp''',
'''ebay.com#\$#hide-if-contains-visible-text /Sponsored/ 'li>div[class="brwrvr__item-card__body"]' 'div>span[class="su-sponsored-label__sep"]>span''',
'''! pp''',
'''ebay.com#\$#hide-if-matches-xpath '//div[@role="text"][text()="Sponsored"]/ancestor-or-self::div[@data-viewport][1]''',
'''! sp''',
'''ebay.*#\$#race start; hide-if-contains-visible-text /Sponsored|Anzeigen|Sponsorisé|Sponsorizzato|Sponsorowane|Gesponsord|Patrocinado|Anzeige/ 'li.s-item' '* li div>span>div ^^sh^^ span:not([aria-hidden="true"])'; hide-if-contains-and-matches-style /./ li[data-viewport] 'li[data-viewport] .s-item__sep>div ^^sh^^ span' /./ 'overflow-x: visible'; hide-if-contains-visible-text /./ 'li[data-viewport]' '.s-item__sep>div ^^sh^^ span:nth-child(2)'; hide-if-matches-computed-xpath './/div[contains(@class, "s-item__detail")]/span/div[@aria-labelledby = "{{}}"]/ancestor::li' './/style[contains(text(),"size: var")]' /^\\s*div\\.(.*?)_/; hide-if-matches-computed-xpath './/div[contains(@class,"s-item__detail")]/span/span[@aria-labelledby="{{}}"]/ancestor::li' './/script[contains(text(),"CSSStyleDeclaration")]' /getPropertyValue\\(\\"\\-\\-(.*?)\\"/; hide-if-matches-computed-xpath './/div[contains(@class,"s-item__detail")]/span/span[@aria-labelledby="{{}}"]/ancestor::li' './/style[contains(text(),"div:first-line")]' '/0px;\\s\\-\\-(.*?)\\:/'; hide-if-matches-computed-xpath './/li//span[@class="s-item__sep"]/span[@aria-labelledby="{{}}"]/ancestor::li' './/div[@id="srp-river-main"]//div[@class="clipped"]/li//span[@aria-labelledby]/..' '/labelledby=\\"(s-.{7})\\"/'; hide-if-matches-computed-xpath './/li//span/span[@aria-labelledby="{{}}"]/ancestor::li' './/div[@id="srp-river-main"]/div[@class="clipped"]/li//span[@aria-labelledby]/..' '/labelledby=\\"(s-.{7})\\"/'; race stop;''',
'''! #CV-737''',
'''cnn.com#\$#strip-fetch-query-parameter caid warnermediacdn.com; strip-fetch-query-parameter afid warnermediacdn.com; strip-fetch-query-parameter conf_csid warnermediacdn.com; strip-fetch-query-parameter app_csid warnermediacdn.com''',
'''||warnermedia.com/api/v1/events?*=ad-break*^\$xmlhttprequest,domain=cnn.com''',
'''cnn.com#\$#override-property-read Object.prototype._setAdsConfigurations noopFunc;''',
'''! #RM-10''',
'''etsy.com#\$#race start; hide-if-contains-visible-text '/[aA](\\s)*d(\\s)*by/' li 'li[class] div > :is(div, p)' 'width: /^[0-9]px/'; hide-if-contains-visible-text '/[aA](\\s)*d(\\s)*b(\\s)*y/' li 'li[class] div > :is(div, p)' 'width: /^[0-9]px/'; race stop;''',
'''etsy.com#\$#hide-if-matches-xpath '//span[@data-is-ad][@data-ad-label][contains(text(),"Ad by")]/ancestor-or-self::li[contains(@class,"wt-grid__item-xs-6")]''',
'''etsy.com#\$#hide-if-matches-xpath './/h2[@class][contains(text(),"By Etsy sellers")]/preceding::p[contains(text(),"Sponsored")]/ancestor-or-self::div[@data-appears-component-name="web_home_strv_ads"]''',
'''etsy.com#\$#hide-if-matches-xpath './/h3[contains(@id,"ad-listing")]/ancestor::li''',
'''etsy.com#\$#hide-if-matches-xpath './/h3[contains(@id,"ad-listing")]/ancestor-or-self::div[@data-page-type="listing_page_similar_listings_grid"]''',
'''etsy.com##a[href*="listing_page_ad_row"]''',
'''! #CV-2993''',
'''www.linkedin.com#\$#simulate-mouse-event 'xpath(//*[text()="Promoted" or text()="Sponsored" or text()="Dipromosikan" or text()="Propagováno" or text()="Promoveret" or text()="Anzeige" or text()="Promocionado" or text()="促銷內容" or text()="Post sponsorisé" or text()="프로모션" or text()="Post sponsorizzato" or text()="广告" or text()="プロモーション" or text()="Treść promowana" or text()="Patrocinado" or text()="Promovat" or text()="Продвигается" or text()="Marknadsfört" or,
  //text()="Nai-promote" or text()="ได้รับการโปรโมท" or text()="Öne çıkarılan içerik" or text()="الترويج"]/ancestor::div[@data-id]//video[@autoplay="autoplay"])\$delay=5';''',
'''! #RM-102''',
'''! #CV-717''',
'''yandex.com#\$#hide-if-contains ad li.serp-item 'li.serp-item div.label''',
'''! #CV-706''',
'''tube8.com##.gridBanner_''',
'''tube8.com##.footerBanner''',
'''youporn.com##[data-track="ad-iframe-top"]''',
'''xhamster.com##div[class\$="no-ts-initiailize"]''',
'''xhamster.com##div[data-role^="yld-pdbanner-underplayer"]''',
'''xhamster.com##div[class*="live-red"]''',
'''xhamster.com#\$#hide-if-matches-xpath './/button[contains(@class,"-close")]/i[@class]/ancestor::span[1]''',
'''spankwire.com#\$#abort-on-property-write ppAb''',
'''tube8.com#\$#abort-on-property-write AdDelivery''',
'''youporn.com,redtube.com#\$#abort-on-property-write rAb''',
'''donk69.com,wankflix.com,mofosex.com,keezmovies.com,extremetube.com,spankwire.com,pornxt.com,crazyshit.com,fantasti.cc,gfjizz.com,smutr.com,yuvutu.com#\$#abort-on-property-read phtData''',
'''redtube.com#\$#abort-on-property-read smpop''',
'''youporn.com#\$#abort-on-property-read zone_underplayer; abort-on-property-read zone_2545''',
'''pornhub.com#\$#abort-on-property-read HTMLElement.prototype.attachShadow; override-property-read page_params.holiday_promo_prem true;''',
'''theyarehuge.com#\$#abort-on-property-read Element.prototype.attachShadow''',
'''||xhamster.com/api/models/vast?*^\$xmlhttprequest,domain=xhamster.com''',
'''! #CV-673''',
'''hotmovs.com##div[class^="vda-closeplay"]''',
'''beeg.com,oral-amateure.com,upornia.com,hotmovs.com,voyeurhit.com,hdzog.com#\$#abort-on-property-write ads_priv''',
'''10bestpornosites.com,123xxx.xyz,141tube.com,18-teen-porn.com,18-teen-sex.com,18-teen-tube.com,18doujin.com,18girlssex.com,18hqporn.com,18teen-tube.com,18teenporno.tv,18tubehd.com,18yed.net,1lesbiantube.com,1piecemanga.com,1teentubeporn.com,1xxx-tube.com,1youngteenporn.com,2017tube.com,2018tube.com,22pixx.xyz,24pornvideos.com,2japaneseporn.com,3devilattack.net,3gaytube.com,3movs.com,3naked.com,3prn.com,3sexporn.com,3xamatorszex.hu,3xfaktor.hu,429tube.com,4archive.org,4asianporn.com,4porn4.com,4tube.com,502porn.com,5299.tv,5star-boys.com,600bottles.com,69-lesbian-sex.com,69teentube.com,6indianporn.com,8asiansex.com,8boobs.com,8muses.xxx,8teenbay.net,8teenxxx.com,8teenz.info,9gag2.com,aagmaal.com,aarleen.com,ablefast.com,absolugirl.com,absoluporn.com,absolutube.com,activeporns.com,activevoyeur.com,acutetube.net,adult-sn.com,adultchatnetworks.com,adultdvdparadise.com,adultxpedia.com,aflamsexnek.com,agedtubeporn.com,agedvideos.com,ah-me.com,ahri-hentai.com,airsextube.com,al4a-archives.com,al4a.com,allafricangirls.net,allbbwtube.com,allfreepornsite.com,allindianporno.com,allmilftube.com,allporncartoons.com,allpussypics.com,allschoolboysecrets.com,allteensnude.net,alltstube.com,allureamateurs.net,alotporn.com,alrincon.com,amateur-twink.com,amateurandreal.com,amateurbeachspy.com,amateurbusters.com,amateurebonypics.com,amateurfun.net,amateurmaturewives.com,amateurmoms.net,amateurpicsporn.com,amateurporn1.com,amateurporntapes.com,amateurs-fuck.com,amateurstreams.pw,amateuryoungpics.com,amazingtrannies.com,anal-analsex-anal.com,analdin.com,analgoals.com,analratings.com,animeindo.cc,animeindo.fun,animejpg.com,animekage.net,annoncesescorts.com,antarvasnastories.com,antavasnasexkahani.com,anusling.info,anynude.net,anyporn.com,anysex.com,arabxnx.com,area51.porn,ariestube.com,artium.org,arturia.com,asian-teen-sex.com,asianbabestube.com,asiancosplayporn.com,asianhamster.com,asianpornphoto.net,asianporntube69.com,asianstubefuck.com,asianteenagefucking.com,asianxxxvideo.net,asiashort.link,astucito.com,atdhe.cc,av-uncen.com,avyahoo.com,axporn.com,babesexpress.com,babesinporn.com,babesjoy.com,babesvagina.com,babeswp.com,babesxworld.com,bananamovies.net,banglachoti-story.com,bangx.org,bangyourwife.com,barfuck.com,barurotero.net,baseballminsk.com,basiltube.com,bbw.com.es,bbw6.com,bbwfest.com,bbwfuckpic.com,bbwpussypics.com,bdsm-fuck.com,bdsm-photos.com,bdsm6tube.com,bdsmporn.cc,bdsmpornfilms.com,bdsmporntub.com,bdsmslavemovie.com,bdsmstreak.com,bdsmwaytube.com,beautyass.com,beegsexporn.com,befap.com,belloporno.com,best-free-sex-stories.com,best-xxxvideos.com,best18teens.com,bestanime-xxx.com,bestblackgay.com,bestfootfetishtube.com,bestgrannies.com,besthentaitube.com,besthugecocks.com,bestjapaneseporn.net,bestlist.top,bestmaturewomen.com,bestofpornreviews.com,bestpussypics.net,bestshemaleclips.com,betterhdporn.com,bigassphotos.com,bigasspictures.net,bigbangtube.com,bigboobs.com.es,bigcocker.com,bigcockgaytube.com,bigcockhub.com,biggestasspics.com,bigtitsxxxfree.com,bigtitsxxxsex.com,birdurls.com,bisexual-mmf-sex.com,bitearns.com,bitfly.io,bitporno.com,black-matures.com,black-porn-pics.org,blackamateursnaked.com,blackchubbymovies.com,blackedtube.com,blackmaturevideos.com,blackpornhq.com,blackpornset.com,blacksexmix.com,blackteen.link,blasensex.com,blowjobamateur.net,blowjobgif.net,blowjobpornset.com,blowxtube.com,blowxxxtube.com,bobolike.com,bobs-tube.com,bolly-tube.com,bollywoodx.org,boobsforfun.com,boolwowgirls.com,booru.eu,borwap.xxx,branitube.net,bravoerotica.com,bravoteens.info,brazzersbabes.com,breedingmoms.com,brokenteen.net,bucetaspeludas.com.br,buonaporno.com,bustmonkey.com,bustybloom.com,bustyfats.com,bustyshemaleporn.com,buttjuiceslurpers.com,callfuck.com,camarads.com,camarchive.tv,camcam.cc,camrouge.com,camuploads.com,camwebtown.com,canalporno.com,cartoonmonstersporn.com,cartoonporncomics.info,cartoonpornpedia.com,cartoonvideos247.com,carvetube.com,cbt-tube.net,cekc-tube.ru,celebrity-leaks.net,celebrityleakednudes.com,celebritynakeds.com,celebsnudeworld.com,centralboyssp.com.br,cercagirl.com,cerdas.com,cfwives.com,chicasdesnudas.xxx,chicoscam.com,chieftube.com,chopris.com,chubbyelders.com,chubbypornmpegs.com,chyoa.com,cinemabg.net,classicpornbest.com,classicpornvids.com,classicxmovies.com,clicporn.com,clipwatching.com,clothing-mania.com,club-flank.com,cockmeter.com,cockpornpics.com,cocksexpics.com,cocogals.com,cocoporn.net,collegeteentube.com,comic-porno.com,comicspornos.com,comicxxx.eu,coolpornblog.com,coquinetv.com,cosepermaschi.it,cosplaypornonline.com,crockotube.com,crossdresserhub.com,crybdsmporn.com,cryptoads.space,csrevo.com,cuckold-videos.org,cuckold.it,cuckoldmature.com,cumlouder.com,cumshotlist.com,cunnilingslist.com,cutieporno.com,czechsex.net,czechvideo.org,dads-banging-teens.com,daftporn.com,dailylesbianporn.com,daporngifs.com,datingfuckdating.com,dawntube.com,debridup.com,decorativemodels.com,deepthroat-porn.com,desihoes.com,desimms.co,desimmshd.com,deutschepornos-kostenlos.com,deutschsex.com,digitalbeautybabes.com,dimtus.com,diniofollando.com,dirtyasiantube.com,dirtybadger.com,dirtyfox.net,dirtygangbangs.com,dirtyporn.cc,dirtytamil.com,dirtytubemix.com,dlouha-videa.cz,do-xxx.com,domahatv.com,domahi.net,domashka.tv,dominantwifeporn.com,donna-cerca-uomo.com,dorevitch.com.au,dosexybabes.com,dotfreesex.com,dotfreexxx.com,doujinshi.rocks,douxporno.com,dragon-ball-super.net,dreamamateurs.com,drsnysvet.cz,drumstube.com,drunkmoms.net,dump.xxx,dumpz.net,easymilftube.net,ebonyamateurphoto.com,ebonyassclips.com,efappy.com,efxx.ru,ehotpics.com,electsex.com,embedy.me,empflix.com,empowher.com,empressleak.biz,en.firstrowi.com,enjoyfuck.com,enormousbabes.net,entertubeporn.com,entrejuegosgratis.com,eporner.com,erett.sex.hu,ero18.cc,erobdsm.com,eroclips.org,erofus.com,erogen.su,eroprofile.com,erospots.info,erotichdworld.com,erotichun.com,eroticteen.com,eroticteensphoto.net,erowall.com,eroxia.com,escort-in-italia.com,escortconrecensione.com,eurocali.it,everysextube.com,exclusiveindianporn.com,exe.app,exgfamateurporn.com,exposedlyrics.com,extremetube.com,ezbit.co.in,faapy.com,family-incest-sex.com,familyporn.tv,familypornhd.com,famosas-desnudas.org,famousnipple.com,famuathletics.com,fantasti.cc,fapality.com,faperplace.com,fapset.com,fatblackmatures.com,fattubevideos.net,fatwhitebutt.com,fatxxxtube.com,favefreeporn.com,fc.lc,fcc.lc,femdom-joi.com,femdomporntubes.com,femdomtube.xxx,femdomworld.com,femjoybabes.com,fetish-bb.com,fetish-tv.com,fetishpornforum.com,fetishshrine.com,ffjav.com,fickenporno.com,fifisex.com,figtube.com,fileone.tv,filestore.to,filleagrosseins.com,filman.cc,filmpornofrancais.fr,filmstreamy.com,filth4you.com,filthydionizos.com,findtranny.com,fineretroporn.com,finevids.xxx,fireporns.com,firstrow1us.eu,firstrowsportes.net,firstsrowsports.com,firstsrowsports.tv,fisting-thumbs.com,fitteasatismerkezi.com,folgenporno.com,forced-porn-thumbs.com,free-gay-clips.com,free-sex-video.net,free-trannyporn.com,freeadultvideos.cc,freeboytwinks.com,freefatpornmovies.com,freegrannypornmovies.com,freegrannyvids.com,freehardpornhub.com,freehindisexstories.com,freehqporn.net,freehqtube.com,freeimagefap.com,freelatinapics.com,freematureasses.com,freematuresexpics.com,freeomovie.info,freepornasia.com,freepornhdonlinegay.com,freepornik.com,freepornjpg.com,freepornstream.cc,freepornstreams.org,freepornvideo.sex,freepornvintage.com,freesex-1.com,freesexgames1.com,freesexvideos24.com,freestreams.eu,freetubegalore.com,freevintageporn.net,freevintagetube.com,freexcelebs.com,freexmovs.com,freexxxvideos.pro,freeyounggayporn.com,freshbbw.com,freshebonytubes.com,freshmaturespussy.com,freshscat.com,freshsexxvideos.com,freshshemaleporn.com,freundinsex.com,freyalist.com,fromasstomouthpics.com,frostytube.com,frprn.com,ftopx.com,fuck-album.com,fuckedbyparents.com,fuckedporno.com,fuckhairygirls.com,fuckhardporn.com,fuckhottwink.com,fuckingsession.com,fuckmilf.net,fuckmimimi.com,fucknsex.com,fucksexybabes.com,fuckslutsonline.com,fuckvideos.adult,fuckvideoshot.com,fuckvideosxxx.com,fullhdxxx.com,fullpornmovies.net,fullxxxmovies.me,fullxxxmovies.net,fullyhd.com,funimg.net,fuqer.com,fuqporn.net,furryporn.xxx,futbolhoy.com.ar,fux.com,gallant-matures.com,gameofporn.com,gangbangasm.com,ganstamovies.com,gatasdatv.com,gay-boys-xxx.com,gay-dicks.com,gay-streaming.com,gayarrangement.com,gaybondagemale.com,gayboyshd.com,gayboystube.com,gayfuckingass.com,gayhardfuck.com,gayporndepot.com,gaypornlove.net,gaypornmasters.com,gaypornwave.com,gaystream.pw,gayteenshd.com,gayvideo.me,gayxxxtube.net,gayyoungporn.com,gcruise.com,generalpornmovies.com,germanxvids.com,get-to.link,getitinside.com,ghettopearls.com,ghostbabes.com,giantshemalecocks.com,giddyteens.com,gifcandy.net,gifsfor.com,gigporntube.com,gir18.com,girl-creampie.com,girl-directory.com,girlfuckgalleries.com,girlnude.link,girls-pron.com,girlsboom.ru,girlscanner.cc,girlssexxxx.com,glamourxxx-online.com,go-xxx-go.com,goatd.me,godjapan.com,gojav.co,goldesel.to,goloeporno.com,gonewild.co,gonzoporn.cc,good-babes.com,goodcomix.tk,gopornindian.com,gosexpod.com,gotporn.com,goxxxvideos.com,grandmatube.pro,grannybeautypics.com,grannycutepics.com,grannyfucko.com,grannyfuckxxx.com,grannypicsdaily.com,grannyporn.name,grannypornpics.com,grannypornpicture.com,grannypornpictures.com,grannysex.name,grannysexphoto.com,grannysexypics.com,grannysfucking.net,grannyslutphoto.com,grannyxxxtube.net,greatestshemales.com,greatnass.com,greensmut.com,greenstrapon.com,grouppornotube.com,grouppornxxx.com,guruofporn.com,guyswithiphones.com,haho.moe,hairy-amateurs.com,hairybeautyphoto.com,hairygirlnaked.com,hairytwat.org,hanimesex.com,hanimesubth.com,happyschlumpftag.com,hardanalsexvideos.com,hardcorehd.xxx,hardcorepornhot.com,hardfacefuck.com,hardsextube.com,hcbdsm.com,hclips.com,hd-analporn.com,hd-freeporn.com,hd-tube-porn.com,hd-world.org,hd-xxx.me,hdbigassporn.com,hdfuckxxx.com,hdgayporn.net,hdjavonline.com,hdmoza.com,hdpicsx.com,hdporn8.com,hdpornole.pl,hdpornpussy.com,hdpornt.com,hdpornteen.com,hdpornzap.com,hdtube.porn,hdtubesex.net,hdzog.com,hentai-hot.com,hentaiarena.com,hentaibrasil.info,hentaicore.org,hentaidream.org,hentaienglish.com,hentaifox.com,hentaifurryporn.com,hentaihand.com,hentaiporn.com.es,hentaiporno.xxx,hentaipulse.com,hentairider.com,hentaitk.net,hentaiwagon.com,hentaiyes.com,heroine-xxx.com,hiddencamhd.com,hindiporno.pro,hindisexkahaniyan.com,hitomi.la,home-made-videos.com,home-xxx-videos.com,homemature.net,homemoviestube.com,hoporno.net,hornbunny.com,hornybitches.org,hornyfanz.com,hornyhotmoms.com,hornyteenpussy.com,hot-sex-tube.com,hotasiadate.com,hotclips24.com,hotgayporn.pro,hotgirl.biz,hotgirlclub.com,hotgirlhub.com,hotjapantubes.com,hotmarathistories.com,hotmaturegirlfriends.com,hotmaturetubes.net,hotmilfgalleries.com,hotmilfpictures.com,hotmirrorpics.com,hotmomsnude.com,hotmomspussy.com,hotmovs.com,hotmoza.com,hotnakedteenporn.com,hotntubes.com,hotnudegirlporn.com,hotpornfile.org,hotpornlove.com,hotpussyhubs.com,hotsexlove.com,hotsexyteen.com,hotsexyteenspics.com,hotstep-mom.com,hotstunners.com,hotteenpornpics.com,hotteensexpics.com,hotvintagetube.net,hotxnxxporn.com,hotyounggirls.net,hqamateurtubes.com,hqhardcoreporno.com,hqsex-xxx.com,hqxxxmovies.com,i-analporn.com,ibradome.com,ideal-teens.com,idealhentai.com,ifreefuck.com,ileak.xyz,ilivestream.com,iluvtoons.com,imagedecode.com,imagenesmy.com,img2share.com,imgadult.com,imgbaron.com,imgclick.net,imgcloud.pw,imgdawgknuttz.com,imgdew.com,imgdew.pw,imgdone.com,imgdrive.net,imgking.xyz,imgkings.com,imgmaid.net,imgmaze.pw,imgnemo.com,imgoutlet.com,imgpeak.com,imgprime.com,imgrock.info,imgrock.net,imgrock.pw,imgsay.com,imgspice.com,imgstudio.org,imgtaxi.com,imgtornado.com,imgtorrnt.in,imgtown.net,imgtown.pw,imzog.com,incontri-in-italia.com,indecentvideos.com,indian-sex-porno-movies-stories.com,indianbestporn.com,indianpornnetwork.com,indianxxx.us,infinityerotic.com,ingyenszexvideok.hu,interflora.co.uk,interflora.ie,ipornia.com,ipornpictures.com,isohunt.lol,isohuntz.net,italianoxxx.com,itasshub.com,iteenpornpics.com,iwantgalleries.com,iwantmature.com,jadsex.net,japaneseasmr.com,japanesefuck.com,japanesemomsex.com,japaneseporndownload.com,japanesepornvideos.net,japanfuck.com.es,japanpornvideo.net,japanstubes.com,japansvids.com,japantaboo.com,japanxxxass.com,japon-porno.com,japornhd.com,jav-xx.com,jav380.com,jav688.com,jav789.com,javbest.xyz,javbix.com,javboys.com,javbuz.com,javfav.com,javgrab.com,javhdfree.net,javhihi.com,javhun.com,javix.net,javkiki.com,javlovers.club,javmelon.com,javnew.net,javonline.space,javpool.com,javrave.club,javteentube.com,javtiful.com,jemontremabite.com,jemontremasextape.com,jemontremonminou.com,jenpornuj.cz,jesseporn.xyz,jigglegifs.com,juicy3dsex.com,juicyflaps.com,juicygif.com,juicygranny.com,justababes.com,justsexpictures.com,kaboomtube.com,kak.xxx,kamasutra-sex-shop.com,kaotic.com,kelly-hu-nude.com,kendralist.com,kenzato.uk,kiaporn.com,kickporn.com,kiminime.com,kingsofteens.com,kinkyporn.cc,kisscartoon.pro,kissdoujin.com,kisshentai.net,kittyfuckstube.com,klaustube.com,klikmanga.com,komikstation.com,komiraw.com,kompoz2.com,korean-sex-video.com,koreancreampie.com,koreansexporn.com,kporno.com,krank.de,kropic.com,ks6col.com,labibledesastuces.com,lanasbigboobs.com,latexgirls.org,latinohentai.com,latinoweb-tv.com,lawanswers.com.au,lesbianic.com,lesbianloveclub.com,lesboluvin.com,letfap.com,lewdweb.net,lightxxxtube.com,likuoo.video,limetorrents.info,line25.com,linkdrop.net,lizardporn.com,ljcam.net,loanadministration.com,lonely-mature.com,longporn.xyz,lovelynudez.com,loverscum.com,lshunters.tv,luscious.net,lushdiaries.com,lustteens.net,lustylist.com,lustyspot.com,lux-teen-pics.com,luxmoms.com,luxviral.com,madchensex.com,mahalogrille.com,mainporno.com,majesticbabes.com,malehardcocks.com,malleys.com,mamisamateur.com,mamochki.info,manga18fx.com,mangamovil.net,mangaonline.fun,mangarussia.com,mangoparody.com,mangoporn.co,mangoporn.net,mangovideo.pw,manikusa.com,marchetravelling.com,massagecreepblog.com,massagefreetube.com,mature-chicks.com,mature-xxx-videos.com,mature4.net,maturegrannypics.com,maturemilfs.net,maturemomhot.com,maturemompics.com,maturemomspics.com,maturepicspussy.com,maturepornjungle.com,maturepornphoto.com,maturepornpics.me,maturesfuck.com,maturesinhd.com,maturewithyoung.com,maturexxxclips.com,maturexxxtube.net,maxcuckold.com,maxtubeporn.net,me-tube.com,meet-women-now.com,megaboobsgirls.com,megafreepics.com,megahugetits.com,megajapansex.com,megaliveporn.com,megapornfreehd.com,megasesso.com,megatube.xxx,meporno.com,miceay.com,miexnoviadesnuda.com,migliori-escort.com,milfhdvideos.com,milfjam.com,milfmomporn.com,milfpussy-sex.com,milfsaloon.com,milfshow.com,milfspics.com,milfspictures.com,milftoon.xxx,mimimiporn.com,misterboys.com,mmhiphopchannel.com,mobifuq.com,mobileasiantube.net,modelsxxxtube.com,mom-fuck.me,mom-pussy.com,mom-x.com,momandyoungboys.com,momjerk.com,mommy-pussy.com,mommyporntube.com,momsfuckdudes.com,momsoclock.com,momspost.com,momsprice.com,momstube-porn.com,momthumb.com,monporntube.com,monsterattack3dporn.com,moregirls.org,morexnxxporn.com,motherandboyvideos.com,movies18.net,moviesinspector.com,moviesxxx.cc,mp4-porn.net,mrcong.com,mrporngeek.com,mrsexe.com,muchfap.com,mujeres-desnudas.com,multporn.net,muschitube.com,musicatorrents.com,musvozimbabwenews.com,mybbwtube.com,mybestxtube.com,mycumx.com,mydesibaba.com,mydesiboobs.com,myfreeecams.mobi,myfreemoms.com,myfreesexpics.com,myfreevintageporn.com,mygalls.com,myhentai.tv,mylust.com,mynakedteens.com,mynudez.com,myp1p.eu,myp2p.biz,mypiratebay.best,mypiratebay.club,mypiratebay.co,mypiratebay.life,mypiratebay.live,mypiratebay.me,mypiratebay.surf,mypiratebay.win,mypiratebay.work,mypiratebay.wtf,mypiratebay.xyz,mypornpics.com,mypornstarbook.net,myreadingmanga.info,mystore.to,myteensexpics.com,myvintageporntube.com,myyoungbabe.com,mzansifun.com,nackte.com,nakedamateurs.link,nakedbbw-sex.com,nakedgirls.link,nakedgirlspornpics.com,nakedmature.sexy,nakedmaturemoms.com,nakedmaturestubes.com,nakedmilfs.sexy,nakedselfphotos.com,nakedteenporn.com,nakenprat.com,nangiphotos.com,nanoporns.com,narutohentaisexxx.com,narutohentaixxxpics.com,nastyhardporn.com,naughtyza.co.za,neatfreeporn.com,neatpornodot.com,needgayporn.com,netfapx.com,netflixporno.net,newchallenges.com.mm,newestxxx.com,newgrandmapictures.com,newretroporn.com,newsextv.com,newtorrentgame.com,newxxxvideos.net,newytstorrent.com,nicemilfpics.com,nicesexytoons.com,nicexxxtube.com,nicheporno.com,nightlifeporn.com,niknieg.com,novinhassafadinhas.com,novoboobs.com,novoerotica.com,novohot.com,nsfw247.to,nsfwalbum.com,nude-beach-tube.com,nude-teen-18.com,nudebabes.sexy,nudeblackgirlfriend.com,nudedxxx.com,nudehotmoms.com,nudematuremilfs.com,nudemomshots.com,nudeperfectgirls.com,nudesexymoms.com,nudeteenporn.com,nudeteenpornsex.com,nudeteenpussy.com,nudevista.at,nudevista.be,nudevista.com.br,nudevista.com.pl,nudevista.es,nudevista.net,nudevista.se,nudeyoungporn.com,nudeyoungteen.com,nudismteens.com,nudistbeach-pics.com,nudisteens.com,nudistic.com,nudistube.com,nurlesben.com,nylonbabez.net,ohueli.net,ok-gay.com,ok.xxx,okporn.com,olalatube.com,older-mature.net,oldgrannylovers.com,oldsluthardcore.com,oldwomanfuck.net,oldwomansex.net,oldwomensex.net,onepunch-manga.com,online-xxxmovies.com,onlinefetishporn.cc,onlinefucktube.com,onlinegrannyporn.com,onlineporn24.com,onlinepornushka.com,onlinesextube.com,onlineteenhub.com,onlinexxx.cc,onlybestxxx.com,onlyfullporn.com,onlygangbang.com,onlygayvideo.com,onlygoldmovies.com,onlyhgames.com,onlylesbianvids.com,onmpeg.com,ooo-maturesex.com,oosex.net,ooxxtube.com,openpirate.org,orgasmlist.com,orgyxxxhub.com,owllink.net,pages4adult.com,palimas.tv,pandamovies.me,pandamovies.pw,pandaporn.net,panduansaya.com,pantyhosecool.com,paralink.com,parapetite.info,parspack.com,passpix.com,pbabes.com,pbangels.com,peachytube.com,pearl-perm.com,pedant.ru,peetube.cc,pelisandseries.net,penis-milking.com,penisbuyutucum.net,perfectgirls.es,perfectgirls.net,perfectgirlspussy.com,perfectnudegirls.com,perfektdamen.co,pervclips.com,pervertedmilfs.com,petitegirlsnude.com,pezporn.com,phatdaddygayporn.com,pic-xxx.com,picbank.tk,pichaloca.com,picmoza.com,picsfuck.org,picspornamateur.com,pictoa.com,picturelol.com,piczki.pl,pinayot.com,pinayviralsexx.com,pinflix.com,pinkporno.com,pinkporno.xxx,pinkteenpics.com,piratebay.cloud,piratebay.live,piratebay.party,piratebay.world,piratebayproxy.live,piratebays.wtf,pirateproxy.live,pirateproxy.surf,pirateproxy.us,pixhost.to,playpornfree.xyz,pleasuregirl.net,plumpxxxtube.com,plusone8.com,poapan.xyz,polochka.net,pomelotube.com,popcorntimes.ws,poringa.net,porn-hd-tube.com,porn-image.net,porn-sexypics.com,porn-star101.com,porn.com,porn.goshow.tv,porn0.tv,porn18sex.com,porn300.com,porn555.com,porn613.net,pornabcd.com,pornbestdirectory.com,pornbestpics.com,pornchaos.org,pornchimp.com,pornclipshub.com,pornclipsxxx.com,porncomics.me,porndaa.com,porndavid.com,porndeva.com,pornditt.com,porndoe.com,porndollz.com,pornerbros.com,porneva.com,pornexpanse.com,pornforrelax.com,pornfreemom.com,porngayclips.com,porngem.com,porngirlstube.com,porngq.com,pornhail.com,pornhat.com,pornhd.com,pornhd8k.me,pornhd8k.net,pornhdin.com,pornhegemon.com,pornhugo.com,pornicom.com,pornj.com,pornkickme.com,pornkino.cc,pornl.com,pornlivehd.com,pornloupe.com,pornlovo.co,pornmaki.com,pornmam.com,pornmaniak.com,pornmaturetube.com,pornmom.net,pornmoms.org,pornnudexxx.com,porno-doma.com,porno-porno.net,porno-up.net,porno-zhena.com,porno01.net,porno666.com,pornoaid.com,pornoanimexxx.com,pornobae.com,pornobengala.com,pornobr.ninja,pornocolegialas.org,pornocrados.com,pornodoido.com,pornodom.tv,pornohaha.com,pornohotxxx.com,pornokeep.com,pornomanoir.com,pornomovies.com,pornone.com,pornonline.cc,pornonote.pro,pornoperra.com,pornoreino.com,pornoserver.eu,pornoteensex.com,pornovideoshub.com,pornovka.cz,pornozot.com,pornpapa.com,pornpy.com,pornrabbit.com,pornrox.com,pornsearchengine.com,pornsex-pics.com,pornsilo.net,pornstarsadvice.com,pornstarsluv.com,porntin.com,porntube.com,porntube18.cc,porntubeplace.net,porntubert.com,porntui.com,porntui.com,pornuploaded.net,pornv.porn,pornvideohunter.com,pornvideoj.com,pornvideos247.com,pornvideoslove.com,pornvideotop.com,pornwatch.ws,pornwatchers.com,pornwhite.com,pornxs.com,pornxxxplace.com,pornxxxvideos.net,pornyeah.com,pornyfap.com,pornzone.com,preggo-pics.com,pregnantsexvids.com,premiumjav.com,primewire.li,priva.us,privateindianmovies.com,pronworld.com,prostoporno.mobi,prostoporno.sexy,prostylex.com,pulandit.com,pure-nudists.com,pureandsexy.org,purenudismpics.com,pussygirls.com,pussyhothub.com,pussymaturephoto.com,pussymoms.com,pussyspace.com,pussyspot.net,pussystate.com,putainporno.com,pvideo.cz,pygodblog.com,pytube.org,qqxnxx.com,queenofmature.com,queerclick.com,queerdiary.com,quincetube.com,rabbitsfun.com,raccontimilu.com,raccontivietati.com,rainytube.com,rapidzona.tv,raptormovies.com,rawindianporn.com,rawofficethumbs.com,real-homemade-movies.com,realbbwsex.com,realbdsmpics.com,realfattube.com,realgfporn.com,realitybrazzers.com,reallatinaporn.com,realvoyeursex.com,reamporn.com,redamateurtube.com,reddflix.com,redgay.net,rednowtube.com,redpornblog.com,redpornnow.com,redtub3xxx.com,redwap.me,reefpiermont.com,regularshowporn.com,relatosdiarios.com,repairlinkshop.com,repicsx.com,retroporn.sexy,rexporn.com,ritzyamateursex.com,ritzyporn.com,ritzysex.com,rl-porevo.net,roma.escortsuper.com,rossoporn.com,rough-teen-sex.com,roughebonysex.com,roughsexpic.com,rounddreams.com,rranime.com,ruedux.com,ruenu.com,rule34hentai.net,rushporn.com,russianmaturetube.com,russkoevideoonline.com,rusteensex.com,saavndownload.com,salooope.com,santoinferninho.com,saradahentai.com,sassytube.com,sassytwinks.com,savelink.site,sawstory.com,scallyguy.com,scorpiotube.com,screenhumor.com,securemeters.com,see-xxx.com,see.xxx,seed69.com,seksrura.net,seneporno.com,sensibleendowment.com,sensualgirls.org,seqing.world,sesso-escort.com,sex-amateur-clips.com,sex-babki.com,sex-pic.info,sex-with-mom.com,sexato.com,sexgay18.com,sexgirlsfucking.com,sexgrandmapics.com,sexhardtubes.com,sexhayvc.com,sexhdtuber.com,sexiestpicture.com,sexlargetube.com,sexmadeathome.com,sexmilf.net,sexmoza.com,sexmv.com,sexoamadorcorno.com,sexocean.com,sexoparalelo.com,sexoverdose.com,sexpuss.org,sexrura.com,sexrura.pl,sextube-6.com,sextubedot.com,sextubent.com,sextubeset.com,sextubexxl.com,sexu.com,sexxxxteenvideo.com,sexy-games.eu,sexy-parade.com,sexy-streaming.com,sexy-youtubers.com,sexyasianteenspics.com,sexybabes.club,sexydilia.com,sexyebonyteen.com,sexyhotteens.com,sexyhub-tube.com,sexykittenporn.com,sexymature.net,sexymaturepussy.com,sexymilfsearch.com,sexynakedgirlspics.com,sexynakeds.com,sexynudetoons.com,sexyoungclips.com,sexyteengirlfriends.net,sexyteenspussy.com,sexytrunk.com,shameless.com,shelovesporn.com,shemalemovies.us,shemalepic.net,shemaleroom.com,shemalestreet.com,shemaletubz.com,shemalez.com,sheshaft.com,shockingmovies.com,short.croclix.me,shwemyanmar.com.mm,silvermilfs.com,simply-hentai.com,singlove.com,sissytube.net,sitarchive.com,skidrowcpy.com,skinnyhq.com,skygals.com,slaughtergays.com,sleazedepot.com,sluktoersten.dk,slutdump.com,sluttyblack.com,smatricom.net,smotret-porno-onlain.com,smplace.com,sokobj.com,sollan.co.il,solopornoitaliani.xxx,somulhergostosa.com,sonorousporn.com,soyoungteens.com,spankwire.com,speedporn.net,spermswapclips.com,spycamsexvideos.com,spycock.com,spyvoyeur.net,sss.xxx,stalkerbt.ru,stepsisterfuck.me,stileproject.com,strangertits.com,stream-69.com,stream2watch.eu,streamextreme.cc,streamhunter.net,streamhunter.top,streaming-ebony.com,streamingporn.xyz,streamporn.cc,streams2watch.me,streamsfinder.com,subdivx.com,submissive-wife.net,submityourflicks.com,sunnyboobs.com,sunporno.com,sunyacc.edu,superbgays.com,supremebabes.com,sweet-maturewomen.com,sweetadult-tube.com,sweetgirl.org,sweetlesbianmovies.com,sweettwinks.com,swipe.xxx,sxyprn.*,szexkepek.net,szexvideok.hu,taboo-dreams.com,tabooporn.tv,taianhsex.com,tamilsexstory.net,tarjetarojaonline.org,taxi69.com,tbib.org,teen-fucktube.com,teen-hd-sex.com,teen-tube-18.com,teen-tube-19.com,teen-tube-21.com,teen-tube-porn.com,teen18hd.com,teenage-nudists.net,teenagefucking.com,teenassporn.com,teenbabe.link,teencamx.com,teenextrem.com,teengirlsporn.com,teenhost.net,teenhubxxx.com,teennudegirls.com,teenpicspussy.com,teenporn-yes.com,teenporn.ws,teenpornjpg.com,teenporntube.xxx,teenporntubea.com,teenpornvideo.xxx,teenpornvideos.me,teens-flashing.com,teens-fucking-matures.com,teensalute.com,teensaura.com,teensex0.com,teensex7.com,teensextube.xxx,teensexvideos.me,teensfuck.me,teenskitten.com,teensneedsex.com,teensonporn.com,teensporn.tv,teenspornpictures.com,teentube-18.com,teenxxxporn.pro,teenyoungpussy.com,telugusexkathalu.com,temptingangels.org,thebarchive.com,theboobsblog.com,thecartoonporntube.com,thedoujin.com,thefamilyguyporn.com,thegay.com,thegay.porn,thehentaiworld.com,thehiddenbay.com,thelesbianporn.com,thematurexxx.com,thepiratebay.org,thepiratebay.zone,thepiratebay0.org,thepiratebay10.org,theshemaletubes.com,theteensexy.com,theyarehuge.com,thisav.com,thisav.video,thisvid.com,thousandbabes.com,tii.ai,timetoteens.com,titsbox.com,tmohentai.com,tnaflix.com,tokyorevengersmanga.com,tomatespodres.com,tomodachinpo.com,tongabonga.com,toonanime.co,topasiantube.net,toplesbianporn.com,topsitestreaming.info,torrent-pirat.com,torrentgalaxy.org,torture1.net,tourporno.com,tpb.party,tpb.red,tpornstars.com,trahodom.com,tranny.one,tranny6.com,trannylibrary.com,trannysexmpegs.com,trannyxxxtube.net,transexuales.gratis,transsexplace.com,tryboobs.com,ts-mpegs.com,tsmovies.com,tstubexxx.com,tube-pornomovs.com,tube-teen-18.com,tube18.sex,tubebikini.com,tubedupe.com,tubedxxx.com,tubeflv.com,tubegaytube.com,tubeline.biz,tubemilfxxx.com,tubepornanal.com,tubepornasian.com,tubepornclassic.com,tubepornnow.com,tubepornstock.com,tuberel.com,tuberl.com,tuberzporn.com,tubes.live,tubesex.me,tubesfuck.com,tubevintageporn.com,tubexo.tv,tubexxxexcellent.com,tubous.com,tubsexer.com,tuhentaionline.com,turbogvideos.com,tvmd.info,tvporn.cc,twatis.com,twinksfuck.me,twinkybf.com,twistedporn.com,uflash.tv,uiz.io,uiz.one,ulsex.net,ultra-sexe.com,ultragranny.com,ultrateenporn.com,uncensoredleak.com,unhas.ac.id,uniqueten.net,uniqxxxtube.com,up-load.io,upicsz.com,upornia.com,uporno.xxx,upskirtporn.de,usaxtube.com,venusarchives.com,ver-mangas-porno.com,verpeliculasporno.gratis,videoporncock.com,videopornoamatoriale.it,videos-xxx.biz,videosdotados.com,videosesso.com,videosputas.xxx,videosxxxporno.gratis,videosxxxputas.com,videoxxx.cc,vidspace.io,vidtube.xxx,viewmature.com,vikiporn.com,vintageporntubes.com,vintagepornvideos.sexy,vintagevideotube.com,vipbox.biz,vipboxing.eu,viralxvideos.es,vivud.com,vixvids.to,vjav.com,vkrovatku.com,voyeurblog.net,voyeurcentre.com,voyeurhit.com,voyeurxxxsex.com,vqporn.com,vqtube.com,vsaporn.com,vzrosliedamy.com,wallpaperspic.pw,wankoz.com,wannafreeporn.com,wantedmovies.com,wantmature.com,watchfreenet.org,watchfreexxx.net,watchfreexxx.pw,watchmyexgf.net,watchporn.cc,watchpornfree.ws,watchseries1.video,watchxxxfree.pw,wauporn.com,waybig.com,webcamsdot.net,webdesigndev.com,webringporn.com,wetpornvideos.net,wetpussy.sexy,wetsins.com,whatav.com,whatsselfies.com,whichav.com,whichav.net,whitepussygoesblack.com,whitexxxtube.com,wifeporn.de,wikimilf.com,wildmaturemoms.com,wildpictures.net,wildretroporn.com,wildteenporn.com,wisiwig.eu,wiziwig.ru,wiziwig.to,wonporn.com,worldsex.com,wow-mature.com,wowasiangirls.com,wowbdsm.com,wowjapangirls.com,wowjapangirls.net,wowpornlist.xyz,wowpornvideos.com,wowxxxtube.com,x-movie7.com,x-videos.name,x24.video,xanimeporn.com,xasiat.com,xbooru.com,xboys.me,xboyzzz.com,xcafe.com,xecce.com,xfilmen.com,xfuckonline.com,xhamsterteen.com,xkeezmovies.com,xlecx.org,xmoviesforyou.net,xnnxfree.com,xnxx-downloader.net,xnxx.irish,xnxx.party,xnxxhamster.net,xnxxpornsex.com,xnxxvideo.pro,xnxxvideoporn.com,xopenload.pw,xpicse.com,xpornfuck.com,xpornphotos.com,xsexpics.com,xspiel.com,xsportshd.com,xstory-fr.com,xtapes.me,xtwinks.me,xvideos-downloader.net,xvideos.name,xvideos.tv.br,xvideosxporn.com,xwhite-tube.com,xxx-asian-tube.com,xxx-babysitters.com,xxx-hd-teens.com,xxx-hd-tube.com,xxx-photo.com,xxx-videos.org,xxx-y.com,xxx3dmobileporn.com,xxx3dmonsters.com,xxx3dsluts.com,xxxadd.com,xxxblowjob.pro,xxxbule.com,xxxcomics.org,xxxery.com,xxxfat-videos.com,xxxfreepornpics.com,xxxhardcoretube.com,xxxholder.com,xxxity.com,xxxkingtube.com,xxxmomsonline.com,xxxmoviestream.xyz,xxxnakedpics.com,xxxnudeteens.com,xxxonline.cc,xxxopenload.com,xxxparodyhd.net,xxxpornotube.net,xxxputas.net,xxxrapid.com,xxxretro.pro,xxxscenes.net,xxxstream.me,xxxstreams.org,xxxtor.com,xxxtubedot.com,xxxtubegain.com,xxxtubenote.com,xxxtubepass.com,xxxtubeset.com,xxxvideor.com,xxxvideostrue.com,xxxxselfie.com,y-porn.com,yes.xxx,yestubemature.com,yeswegays.com,yetimovies.com,yify-films.com,yoerotica.com,yogranny.com,youandjizz.com,youfreepornotube.com,young-ass.com,young-pussy.com,youngbelle.net,youngerasiangirl.net,youngerporn.mobi,youngpornpics.com,youngpornpussy.com,youngsex0.com,youngsexpics.com,youngsexygfs.com,youngteensporn.com,youngvirgingirls.com,youplayhere.com,youpornfm.com,your-daily-girl.com,youramateurtube.com,yourbitches.com,yourhomemadetube.com,yourlust.com,yourlust.mobi,yourtranny-sex.com,yousexvideos.net,youvideoporno.mobi,youwatchporn.com,ytanime.tv,yumstories.com,zbporn.com,zenfield.pro,zhlednito.cz#\$#abort-current-inline-script document.dispatchEvent myEl; abort-on-property-read aNB; abort-on-property-read BetterJsPop; abort-on-property-read ExLdr.serve; abort-on-property-read exoDocumentProtocol; abort-on-property-read ExoLoader; abort-on-property-read ExoLoader.addZone; abort-on-property-read ExoLoader.serve; abort-on-property-read exoNoExternalUI38djdkjDDJsio96; abort-on-property-read ExoooLoooader; abort-on-property-read getexoloader; abort-on-property-read popit;''',
'''mangovideo.pw#\$#abort-on-property-write puShown''',
'''zbporn.com#\$#abort-on-property-read popns''',
'''nsfwalbum.com#\$#abort-current-inline-script document.getElementsByTagName body''',
'''hclips.com#\$#abort-on-property-read btoa''',
'''hentaiworld.tv,manhwaclub.net,masahub.net#\$#abort-on-property-read __formatsGetters''',
'''! #CV-688''',
'''@@||st.bebi.com/bebi_v3.js\$script,domain=lolhentai.net''',
'''/*gek|\$image,domain=animenova.org|animeplus.tv|gogoanimes.co|gogoanimes.fi|kiss-anime.ws|readcomiconline.to|mangareader.net|animewow.org|animeland.us''',
'''/*Rek|\$image,domain=animenova.org|animeplus.tv|gogoanimes.co|gogoanimes.fi|kiss-anime.ws|readcomiconline.to|mangareader.net|animewow.org|animeland.us''',
'''/wp-includes/css/admin-bar.min.css^\$script,domain=kiss-anime.ws|animeland.us|thewatchcartoononline.tv''',
'''/jsvendor/app.^\$script,image,domain=kickassanime.io''',
'''/Scripts/jquery.min.js^\$script,domain=readcomiconline.to''',
'''/assets*\$script,image,domain=kickassanime.io''',
'''/cache2/*\$script,image,domain=watchcartoonsonline.eu''',
'''/wp-includes/js/jwplayer.js?\$script,image,domain=watchcartoonsonline.eu''',
'''/homepage*\$script,image,domain=kickassanime.io''',
'''kickassanime.io##.ka-ax-wrapper''',
'''/sid*\$domain=kickassanime.io''',
'''/mya/lfa.js\$domain=thewatchcartoononline.tv|wcostream.com''',
'''mangareader.net,kiss-anime.ws,animeland.us#\$#abort-on-property-read bbHideDiv''',
'''narutohentaidb.com#\$#abort-on-property-write BackDropNar; hide-if-matches-xpath './/canvas[contains(@style,"padding")]/ancestor::div[contains(@style,"z-index")][1]';''',
'''! #CV-659''',
'''filmxy.one##.promo-contents''',
'''y2mate.com#\$#abort-on-property-read dispatchEvent; abort-on-property-read window.open;''',
'''! #CV-761''',
'''! Experimental filters''',
'''||facebook.com/xti.php?''',
'''||facebook.net^*/fbevents.js\$third-party''',
'''||facebook.com/tr\$third-party''',
'''||connect.facebook.net^*/fbds.js\$third-party''',
'''! #CV-661''',
'''marketrealist.com,kansas.com,thenewstribune.com#\$#abort-on-property-read \$aproxy''',
'''9to5mac.com,9to5google.com,9to5toys.com##iframe[data-google-container-id]''',
'''9to5mac.com,9to5google.com,9to5toys.com##iframe[title="Advertisement"]''',
'''9to5mac.com,9to5google.com,9to5toys.com,marketrealist.com,electrek.co,dronedj.com##iframe[title="3-rd party ad content"]''',
'''9to5toys.com##div[id^="jrrjoh_dgv_liudph_/1049447"]''',
'''9to5toys.com##iframe[id="jrrjoh_dgv_iudph1"]''',
'''marketrealist.com##div[data-google-query-id]''',
'''marketrealist.com##iframe[data-creative-load-listener]''',
'''marketrealist.com##iframe[data-apb]''',
'''marketrealist.com##iframe[data-kiosked-adframe]''',
'''marketrealist.com##div[data-kiosked-role="ad-container"]''',
'''marketrealist.com##.kskdDiv''',
'''marketrealist.com##body[onload="createDyTag();"]''',
'''marketrealist.com##img[onload="\$aproxy.fetch_cookies(this)"]''',
'''marketrealist.com##.GoogleCreativeContainerClass''',
'''||marketrealist.com/3:\$subdocument,domain=marketrealist.com''',
'''! #CV-763''',
'''dailymail.co.uk##.billboard''',
'''dailymail.co.uk##.puff-ad''',
'''dailymail.co.uk##.sliding_mpu''',
'''dailymail.co.uk##.molads_sky_left_top''',
'''dailymail.co.uk##.molads_sky_right_top''',
'''dailymail.co.uk###billBoard''',
'''dailymail.co.uk###js-sky-right''',
'''dailymail.co.uk###js-sky-left''',
'''dailymail.co.uk##[name^="google_ads_iframe_"]''',
'''! #CV-243''',
'''mediafire.com#\$#abort-on-property-read UAParser''',
'''! #CV-679''',
'''quora.com##.u-margin-top--lg+div[class="UnifiedAnswerPagedList PagedListFoo unified"][id\$="_paged_list"]''',
'''quora.com##.pagedlist_item > div[id\$="_paged_list"]''',
'''quora.com##.answer_auto_expanded_comments + div > div.feed_expand''',
'''quora.com##.feedback_wrapper.hidden:not(.negative_action) + .FeedStory.HyperLinkFeedStory.feed_item''',
'''quora.com##div[class="question_main_col"]  > div:nth-child(3) > div[class="UnifiedAnswerPagedList PagedListFoo unified"]''',
'''quora.com##div[class="pagedlist_item"]  div[id*="paged_list"]''',
'''quora.com##.q-box.qu-borderAll>.q-box>div>div[class^="Box-sc-"]>div:not([class])''',
'''quora.com##.spacing_log_question_page_ad''',
'''quora.com##.q-box.qu-borderTop>[class^="Box-sc-"]>div:not([class])''',
'''quora.com##div > [class^="Box-"] > div > .q-box.qu-pb--tiny.qu-pt--medium.qu-px--medium''',
'''quora.com##.qu-bg--white>[class^="Box-"] .qu-pt--medium''',
'''quora.com##.q-box.qu-borderTop>[class^="Box-"] .q-box.qu-pt--medium.qu-pb--tiny''',
'''quora.com##.q-box.qu-borderAll>.q-box>div:not([class="q-box"])>[class^="Box-"]''',
'''quora.com##.q-box.qu-borderAll.qu-bg--white>.q-box>div>[class="q-box "]>[class="q-box"]''',
'''quora.com##[class="q-box qu-borderTop"]>[class="q-box "]''',
'''quora.com##[class="q-box qu-bg--white"]>[class="q-box "]>[class="q-box"]''',
'''quora.com##.q-box.qu-bg--white > span[data-nosnippet="true"] > .q-box''',
'''quora.com##.qu-mb--small.qu-bg--white > .q-box > div > span[data-nosnippet="true"] > .q-box''',
'''quora.com##.q-box.qu-borderTop > span[data-nosnippet="true"] > .q-box''',
'''quora.com##span[data-nosnippet="true"] .q-box.qu-pb--tiny.qu-pt--medium''',
'''quora.com##span[data-nosnippet="true"] .q-box.qu-pt--medium''',
'''quora.com##span[data-nosnippet="true"] .q-box.dom_annotate_ad_image_ad''',
'''quora.com##span[data-nosnippet="true"] .q-box.dom_annotate_ad_video_ad''',
'''quora.com##.dom_annotate_ad_promoted_answer''',
'''quora.com##.dom_annotate_multifeed_bundle_AdBundle''',
  ];
  log('1');
  log(rules.length.toString());
  Stopwatch stopwatch = Stopwatch()..start();
  final List<Filter> filters = [];
  for (final rule in rules) {
    try {
      final filter = Filter.fromText(rule);
      filters.add(filter);
    } catch (e) {
      print('Error parsing rule $rule: $e');
    }
  }
  print('Time: ${stopwatch.elapsedMilliseconds} ms');
  stopwatch.stop();
  log(filters.length.toString());
  final url = URLRequest("https://www.d2wlwbnaa4keje.cloudfront.net", null);
  final firstFilter = filters[0];
  log(firstFilter.toString());
  log(firstFilter.type);
  final blocked = (firstFilter is URLFilter) && firstFilter.matches(url, ContentType.IMAGE, null);
  log("Is URLFilter: $blocked");
}
