name: adblock_rule_parser
description: A Dart implementation of AdBlock filter rules parser
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  meta: ^1.9.0
  logger: ^2.5.0

dev_dependencies:
  test: ^1.24.0
  lints: ^2.1.0
